Add caching for account address balance computation
MystenLabs/sui pull request #10693
Opened 2023-04-11 00:04 UTC by sadhansood

## Description 

Add a cache which caches the account balance and invalidates it whenever coin ownership changes. This prevents background db access when coin ownership has not changed.

## Test Plan 

Existing tests, going to add some tests as well.

2023-04-17 20:39 UTC, longbowlu commented on crates/sui-storage/src/indexes.rs
> +    }
remove?

2023-04-17 21:18 UTC, longbowlu commented on crates/sui-storage/src/indexes.rs
> +                        .acquire_lock((owner.0, type_tag.clone()))
I think it's helpful to merge `invalidate_deleted_coins` and `invalidate_added_coins` so only need to acquire the write lock once for `per_coin_rw_locks`

2023-04-17 22:07 UTC, sadhansood commented on crates/sui-storage/src/indexes.rs
> +        }
done

2023-04-17 22:07 UTC, sadhansood commented on crates/sui-storage/src/indexes.rs
> +        self.invalidate_deleted_coins(&object_index_changes.deleted_owners)
done

2023-04-17 22:07 UTC, sadhansood commented on crates/sui-storage/src/indexes.rs
> +                    };
done

2023-04-18 01:01 UTC, longbowlu approved these changes

2023-04-18 01:07 UTC, sadhansood commented on crates/sui-proc-macros/src/lib.rs
> +                let _cache = ::sui_simulator::moka::sync::Cache::<String, i32>::new(100);
This is to fix non determinism in simtest code

2023-04-18 01:08 UTC, sadhansood commented on crates/sui-storage/src/indexes.rs
> +                "Total number of balance request served ",
done

2023-04-18 01:08 UTC, sadhansood commented on crates/sui-storage/src/indexes.rs
> +                address_coin_type_to_invalidate.insert((*owner, coin_type_tag.clone()));
It might be another refactor, let's do it if it seems like a problem

2023-04-18 03:32 UTC, bmwill requested changes

2023-04-18 03:32 UTC, bmwill commented on crates/sui-core/tests/staged/sui.yaml
> -AbortLocation:
Do not delete this file. This is critical to ensure we are not breaking compatibly

2023-04-18 13:51 UTC, merged