[explorer] paginated epochs table
MystenLabs/sui pull request #11141
Opened 2023-04-20 18:46 UTC by Nikhil-Mysten

## Description 

Describe the changes or additions included in this PR.

## Test Plan 

How did you test the new or updated feature?

---
If your changes are not user-facing and not a breaking change, you can skip the following section. Otherwise, please indicate what changed, and then add to the Release Notes section as highlighted during the release process.

### Type of Change (Check all that apply)

- [ ] user-visible impact
- [ ] breaking change for a client SDKs
- [ ] breaking change for FNs (FN binary must upgrade)
- [ ] breaking change for validators or node operators (must upgrade binaries)
- [ ] breaking change for on-chain data layout
- [ ] necessitate either a data wipe or data migration

### Release notes

2023-04-24 16:10 UTC, Jibz-Mysten commented on apps/explorer/src/hooks/useGetEpochs.ts
> +        async ({ pageParam }) =>
Nit, no need for async await.  you can also `({ pageParam = null })` and ` getNextPageParam: ({ nextCursor, hasNextPage }) => hasNextPage ? nextCursor : null`

2023-04-24 16:10 UTC, plam-ml reviewed
lgtm, but let's wait for 1 more review

2023-04-24 16:10 UTC, plam-ml commented on apps/explorer/src/components/Activity/utils.tsx
> +
remove extra space

2023-04-24 16:10 UTC, plam-ml commented on apps/explorer/src/components/Activity/utils.tsx
> +
remove extra space

2023-04-28 17:46 UTC, mystie711 commented
could we take care of the misaligned table column headers @Nikhil-Mysten ?
<img width="117" alt="image" src="https://user-images.githubusercontent.com/109102528/235217535-25456bfb-252a-4b6c-b592-635417147928.png">

2023-04-28 18:32 UTC, mamos-mysten requested changes

2023-04-28 18:32 UTC, mamos-mysten commented on apps/explorer/src/components/Activity/EpochsActivityTable.tsx
> +                        'Storage Revenue',
this was updated to Storage Net Infow

2023-04-28 19:16 UTC, mamos-mysten approved these changes

2023-05-01 14:44 UTC, merged