Fix Writing a package section of Move doc
MystenLabs/sui pull request #1172
Opened 2022-03-31 18:48 UTC by Clay-Mysten

Fix Writing a package section of Move doc

2022-03-31 19:14 UTC, huitseeker commented on doc/src/build/move.md
> +described in [Contributing to Sui](../contribute/index.md#download-and-learn-sui)
Linebreak?

2022-04-04 16:17 UTC, awelc requested changes

2022-04-04 16:27 UTC, Clay-Mysten commented on doc/src/build/move.md
> +Navigate (`cd`) into the `sui` directory and run:
Ahh, I see now. Let me rework this change given that intention. Thanks!

2022-04-04 20:57 UTC, Clay-Mysten commented on doc/src/build/move.md
> +Navigate (`cd`) into the `sui` directory and run:
I've now put this back in order. Sorry for my confusion.

2022-04-04 21:07 UTC, merged