[Explorer]: update type args
MystenLabs/sui pull request #12368
Opened 2023-06-06 19:58 UTC by plam-ml

## Description 

- Add missing bracket around type args

## Test Plan 

How did you test the new or updated feature?

---
If your changes are not user-facing and not a breaking change, you can skip the following section. Otherwise, please indicate what changed, and then add to the Release Notes section as highlighted during the release process.

### Type of Change (Check all that apply)

- [ ] protocol change
- [ ] user-visible impact
- [ ] breaking change for a client SDKs
- [ ] breaking change for FNs (FN binary must upgrade)
- [ ] breaking change for validators or node operators (must upgrade binaries)
- [ ] breaking change for on-chain data layout
- [ ] necessitate either a data wipe or data migration

### Release notes

2023-06-06 21:11 UTC, mamos-mysten requested changes

2023-06-06 21:11 UTC, mamos-mysten commented on apps/explorer/src/pages/transaction-result/programmable-transaction-view/Transaction.tsx
> +    console.log('data', data);
console.log

2023-06-06 21:37 UTC, Jibz-Mysten approved these changes

2023-06-07 21:38 UTC, mamos-mysten approved these changes

2023-06-07 21:56 UTC, merged