Explorer transaction mock
MystenLabs/sui pull request #1269
Opened 2022-04-07 00:43 UTC by stella3d

Here's a single mock transaction's details to unblock explorer front-end work.

The included typescript types try to account for the fact that we are in flux between using number-array encoding of bytes and using `base64` encoding.  If they differ from what's in the included json, use what's in the json.  

I'll get some more examples soon.

2022-04-07 15:17 UTC, Andrew47 requested changes
This is a good start. I particularly like the idea of splitting the static JSON data across multiple files. We'll need `findDataFromID` to be updated to tap into these various JSON datasets. Perhaps if there were a script that pulled from across JSON files and exported a single data item?

2022-04-07 15:17 UTC, Andrew47 commented on explorer/client/src/utils/internetapi/mock_transactions.json
> +[
Given this is static JSON data, the directory `explorer/client/src/utils/static` would be a more suitable directory. The `findDataFromID` function in `src/utils/static/searchUtil` can then be updated to search across the multiple different static JSON files.

2022-04-07 15:17 UTC, Andrew47 commented on explorer/client/src/utils/static/movecall-tx-response.json
> +{
This JSON file is in the correct directory; although `findDataFromID` will need to tap into this JSON file also.

2022-04-08 05:31 UTC, 666lcz reviewed
Thanks for defining all these types! I can copy & paste most of them to the formal SDK

2022-04-08 05:31 UTC, 666lcz commented on explorer/client/src/utils/internetapi/TransactionTypes.ts
> +    sigs: AuthorityNameSigPair[]        // signatures
Why do we want to change the field names here? This makes deserialization harder and more error prone

2022-04-08 05:31 UTC, 666lcz commented on explorer/client/src/utils/internetapi/TransactionTypes.ts
> +    is_checked: boolean,
`is_checked` is marked as `skip` [here](https://github.com/MystenLabs/sui/blob/f9ef1783083bc5011951ae3a779bb70d27cb8335/sui_types/src/messages.rs#L333), so it seems that this field won't be sent to the client side?

2022-04-14 15:47 UTC, Clay-Mysten reviewed
Markdown LGTM

2022-04-21 17:07 UTC, stella3d commented
closing this because data format has changed.  easier to redo

2022-04-21 17:07 UTC, closed without merging