fix: fix no CA certificates error
MystenLabs/sui pull request #13265
Opened 2023-08-02 11:19 UTC by fredliang44

## Description 

Current sui-node Dockerfile dont have `ca-certificates`, causing `mysten/sui-node` docker image not able to start with error `no CA certificates error`

This PR added  `ca-certificates` to dockerfile to avoid sui-node docker directly exit when starting.

## Test Plan 

How did you test the new or updated feature?

---
If your changes are not user-facing and not a breaking change, you can skip the following section. Otherwise, please indicate what changed, and then add to the Release Notes section as highlighted during the release process.

### Type of Change (Check all that apply)

- [ ] protocol change
- [ ] user-visible impact
- [ ] breaking change for a client SDKs
- [ ] breaking change for FNs (FN binary must upgrade)
- [ ] breaking change for validators or node operators (must upgrade binaries)
- [ ] breaking change for on-chain data layout
- [ ] necessitate either a data wipe or data migration

### Release notes

2023-08-02 11:24 UTC, fredliang44 commented
@ebmifa Hi, the current Testnet's docker image is unable to start due to the lack of this package. We hope to merge this PR before the next mainnet version is released, to prevent encountering this issue when ecosystem projects are upgraded.

2023-08-02 15:25 UTC, bmwill approved these changes

2023-10-10 16:50 UTC, after-ephemera requested changes
This should have already been addressed at this point. Please feel free to correct me if I'm wrong or close out this PR.

2023-10-10 17:18 UTC, closed without merging

2023-10-10 17:18 UTC, bmwill commented
As @after-ephemera mentioned this should be addressed now, if not feel free to reopen