Deterministic Builds
MystenLabs/sui pull request #13844
Opened 2023-09-19 16:19 UTC by RyanSquared

## Description 

Bit-for-bit deterministic rebuilds using pinned Debian artifacts in Docker.

## Test Plan 

On this branch, run `make`, and run `sha256sum out/sui-node`. The value returned should be `70aad1239eb287f33cca4e18cb0d1e7f217aad55f79b3d7574d106a5828c2a72`.

Previously tested by @jnaulty.

2023-09-22 20:03 UTC, bmwill requested changes

2023-09-22 20:03 UTC, bmwill commented on fetch/apt/zlib1g-dev_1%3a1.2.13.dfsg-1_amd64.deb
I would prefer not having a dependency on Git LFS, this requires that these artifacts are stored *somewhere* and instead of using git to fetch these we should probably rely on build tooling to do this for us.

2023-09-22 20:06 UTC, jnaulty commented
Relates to: https://github.com/MystenLabs/sui/issues/13476

2023-09-22 20:32 UTC, RyanSquared commented on fetch/apt/zlib1g-dev_1%3a1.2.13.dfsg-1_amd64.deb
The usage of Git LFS is to avoid slowness when interacting with the Debian snapshots repository. @lrvick mentioned on a call last night that they can be stored in an S3 bucket. I personally have not done this before, so I will defer to him on the best practice for this.

2023-09-22 20:33 UTC, RyanSquared commented on .gitattributes
> +fetch/apt/ncurses-bin_6.4-4_amd64.deb filter=lfs diff=lfs merge=lfs -text
These are the system programs and libraries required to run toolchain and build `sui`. I believe a wildcard would work, I will test it out.

2023-09-22 20:34 UTC, RyanSquared commented on .gitmodules
> +	url = https://codeberg.org/distrust/toolchain
So instead of including a Git submodule, it would be cloned from the Makefile?

2023-09-22 20:40 UTC, RyanSquared commented on fetch/apt/zlib1g-dev_1%3a1.2.13.dfsg-1_amd64.deb
Another alternative is to host a Debian mirror with the required packages.

2023-10-06 15:20 UTC, bmwill approved these changes

2023-10-11 00:08 UTC, jnaulty approved these changes
Thanks 
This PR helps with #13476 

Current repo to build deterministically is: https://git.distrust.co/public/sui-build

2023-10-11 14:25 UTC, merged