[Docker] fix docker compose
MystenLabs/sui pull request #13988
Opened 2023-09-27 00:43 UTC by mwtian

## Description 

Make some fixes to make docker compose work on the latest `main` branch.

## Test Plan 

```
sui/docker/sui-node $ sudo ./build.sh -t sui-node-local
~/fullnode/docker $ wget https://github.com/MystenLabs/sui-genesis/raw/main/devnet/genesis.blob
~/fullnode/docker $ cp ~/sui/crates/sui-config/data/fullnode-template.yaml ./
# Update docker label to sui-node-local
~/fullnode/docker $ cp ~/sui/docker/fullnode/docker-compose.yaml ./
~/fullnode/docker $ sudo docker compose up
```

---
If your changes are not user-facing and not a breaking change, you can skip the following section. Otherwise, please indicate what changed, and then add to the Release Notes section as highlighted during the release process.

### Type of Change (Check all that apply)

- [ ] protocol change
- [ ] user-visible impact
- [ ] breaking change for a client SDKs
- [ ] breaking change for FNs (FN binary must upgrade)
- [ ] breaking change for validators or node operators (must upgrade binaries)
- [ ] breaking change for on-chain data layout
- [ ] necessitate either a data wipe or data migration

### Release notes

2023-09-27 10:15 UTC, teohaik requested changes
@mwtian 
docker-compose.yml does not work on Windows, Error: 

```
Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "/opt/sui/bin/sui-node": stat /opt/sui/bin/sui-node: not a directory
: unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type
```

2023-09-27 10:20 UTC, teohaik commented
Inspecting the created container reveals that `bin `is actually the executable and not a folder, as the command in docker-compose.yml implies:
`command: ["/opt/sui/bin/sui-node"`
![image](https://github.com/MystenLabs/sui/assets/1785012/ed9f4aba-b907-40c5-9f3c-74283cc7f555)

The root cause for this is probably here, in the Dockerfile:

```
# Both bench and release profiles copy from release dir
COPY --from=builder /sui/target/release/sui-node /opt/sui/bin
```

2023-09-27 11:45 UTC, teohaik commented
**Update**:
Built the new image locally and tried again the `docker compose up` on Windows. 
Getting error:
```
2023-09-27 14:43:48 fullnode-fullnode-1  | thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Is a directory (os error 21)
2023-09-27 14:43:48 fullnode-fullnode-1  | 
2023-09-27 14:43:48 fullnode-fullnode-1  | Caused by:
2023-09-27 14:43:48 fullnode-fullnode-1  |     Is a directory (os error 21)
2023-09-27 14:43:48 fullnode-fullnode-1  | 
2023-09-27 14:43:48 fullnode-fullnode-1  | Stack backtrace:
2023-09-27 14:43:48 fullnode-fullnode-1  |    0: sui_config::Config::load
2023-09-27 14:43:48 fullnode-fullnode-1  |    1: sui_node::main
2023-09-27 14:43:48 fullnode-fullnode-1  |    2: std::sys_common::backtrace::__rust_begin_short_backtrace
2023-09-27 14:43:48 fullnode-fullnode-1  |    3: std::rt::lang_start::{{closure}}
2023-09-27 14:43:48 fullnode-fullnode-1  |    4: std::rt::lang_start_internal
2023-09-27 14:43:48 fullnode-fullnode-1  |    5: main
2023-09-27 14:43:48 fullnode-fullnode-1  |    6: __libc_start_main
2023-09-27 14:43:48 fullnode-fullnode-1  |    7: _start', crates/sui-node/src/main.rs:38:58
2023-09-27 14:43:48 fullnode-fullnode-1  | stack backtrace:
2023-09-27 14:43:48 fullnode-fullnode-1  |    0:     0x5654154504ba - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::he1c117e52d53614f
2023-09-27 14:43:48 fullnode-fullnode-1  |    1:     0x56541547ad9e - core::fmt::write::h25eb51b9526b8e0c
2023-09-27 14:43:48 fullnode-fullnode-1  |    2:     0x565415449775 - std::io::Write::write_fmt::ha9edec5fb1621933
2023-09-27 14:43:48 fullnode-fullnode-1  |    3:     0x565415450285 - std::sys_common::backtrace::print::h41b9b18ed86f86bd
2023-09-27 14:43:48 fullnode-fullnode-1  |    4:     0x565415451d1f - std::panicking::default_hook::{{closure}}::h22a91871f4454152
2023-09-27 14:43:48 fullnode-fullnode-1  |    5:     0x565415451a5b - std::panicking::default_hook::h21ddc36de0cd4ae7
2023-09-27 14:43:48 fullnode-fullnode-1  |    6:     0x565415452429 - std::panicking::rust_panic_with_hook::h5059419d6d59b3d0
2023-09-27 14:43:48 fullnode-fullnode-1  |    7:     0x5654154521c9 - std::panicking::begin_panic_handler::{{closure}}::h0f383c291cd78343
2023-09-27 14:43:48 fullnode-fullnode-1  |    8:     0x56541545096c - std::sys_common::backtrace::__rust_end_short_backtrace::h70ab22f2ad318cdd
2023-09-27 14:43:48 fullnode-fullnode-1  |    9:     0x565415451ed2 - rust_begin_unwind
2023-09-27 14:43:48 fullnode-fullnode-1  |   10:     0x565412de6893 - core::panicking::panic_fmt::hd1d46bcde3c61d72
2023-09-27 14:43:48 fullnode-fullnode-1  |   11:     0x565412de6d43 - core::result::unwrap_failed::h456a23f68607268c
2023-09-27 14:43:48 fullnode-fullnode-1  |   12:     0x5654132816d1 - sui_node::main::hd2a8c75563d933f6
2023-09-27 14:43:48 fullnode-fullnode-1  |   13:     0x56541300a303 - std::sys_common::backtrace::__rust_begin_short_backtrace::h4e83ad20fd26d566
2023-09-27 14:43:48 fullnode-fullnode-1  |   14:     0x565413148069 - std::rt::lang_start::{{closure}}::h9d1bc31251b5727e
2023-09-27 14:43:48 fullnode-fullnode-1  |   15:     0x5654154417ec - std::rt::lang_start_internal::h8f7e70b1a2558118
2023-09-27 14:43:48 fullnode-fullnode-1  |   16:     0x56541328173c - main
2023-09-27 14:43:48 fullnode-fullnode-1  |   17:     0x7f94696a2d0a - __libc_start_main
2023-09-27 14:43:48 fullnode-fullnode-1  |   18:     0x565412e09c9a - _start
2023-09-27 14:43:48 fullnode-fullnode-1  |   19:                0x0 - <unknown>
```

2023-09-27 15:44 UTC, mwtian commented
@teohaik did you update the genesis blob path in `fullnode-template.yaml`?

2023-09-28 07:50 UTC, teohaik commented
They are in the same folder, but 
1. they appear as folders, not files
2. they are empty

![image](https://github.com/MystenLabs/sui/assets/1785012/81227d00-b999-447b-b9c9-c15b56b8ec03)
![image](https://github.com/MystenLabs/sui/assets/1785012/1e81cd5c-9ddf-4018-a5f0-5682e0c4d2a7)

2023-09-28 15:21 UTC, mwtian commented
Yeah I'm not sure about the Windows equivalent commands, but deleting the folders and copying the intended files over should at least help you make progress.

2023-10-02 11:19 UTC, teohaik commented
@mwtian  copied the `fullnode-template.yaml` from `crates/sui-config` and downloaded `genesis.blob` from here as the readme says:
wget https://github.com/MystenLabs/sui-genesis/raw/main/devnet/genesis.blob

but getting error again:



```
2023-10-02 14:15:39 fullnode-fullnode-1  | 2023-10-02T11:15:39.150383Z  INFO sui_node: Sui Node version: 1.2.0-69b839d13-dirty
2023-10-02 14:15:39 fullnode-fullnode-1  | 2023-10-02T11:15:39.153725Z  INFO sui_node: Supported protocol versions: Some(SupportedProtocolVersions { min: ProtocolVersion(1), max: ProtocolVersion(11) })
2023-10-02 14:15:39 fullnode-fullnode-1  | 2023-10-02T11:15:39.157781Z  INFO sui_node: Started Prometheus HTTP endpoint at 0.0.0.0:9184
2023-10-02 14:15:39 fullnode-fullnode-1  | 2023-10-02T11:15:39.162712Z  INFO sui_node: Initializing sui-node listening on /dns/localhost/tcp/8080/http node=k#acbf88728815bfd4c2b2ca89b4b0a9f0a3d2bb2a6e2f23c708180686e7e84489f878741e2025cf79e366cc690681cd4905edaac67557ee1037c9338ce9def3082a6fdfd265e885c4f8eac555f3e7fdaa94cf515607967e289499ca2a1f1dc3a5
2023-10-02 14:15:39 fullnode-fullnode-1  | 2023-10-02T11:15:39.724467Z  INFO sui_core::authority::authority_store: Creating new epoch start config from genesis
2023-10-02 14:15:39 fullnode-fullnode-1  | 2023-10-02T11:15:39.746393Z  INFO sui_core::authority::authority_store: Epoch start config: V2(EpochStartConfigurationV2 { system_state: V1(EpochStartSystemStateV1 { epoch: 0, protocol_version: 26, reference_gas_price: 1000, safe_mode: false, epoch_start_timestamp_ms: 1695662552404, epoch_duration_ms: 86400000, active_validators: [EpochStartValidatorInfoV1 { sui_address: 0xd10db16288cd4d5bf157348c6940f4ffad3fab434c6f0959883049ac9e7e6664, protocol_pubkey: iJaHCwrJQ5O5ny0Rzc/vKhG6cJeHMdBPrr4IK7ABBoIDPIFvf9bSHebHMfmmuDAbGClcah+V+n0/g5GhJzJEiuZ/hWJLDaOfh4ovwVg1F+iYhr0y0fPvD/UMhQYNHAa9, narwhal_network_pubkey: c734Ruaz8ZpPmGJdioe3JfbbAlm78RPa6o6aG6JQcqg=, narwhal_worker_pubkey: r0+lWrvk+O0MOLrsde+xbeSK7G47LTZ3J3PpqDNMHCE=, sui_net_address: Multiaddr("/dns/ewr-suival-a4bdd.devnet.sui.io/tcp/8080/http"), p2p_address: Multiaddr("/dns/ewr-suival-a4bdd.devnet.sui.io/udp/8084"), narwhal_primary_address: Multiaddr("/dns/ewr-suival-a4bdd.devnet.sui.io/udp/8081"), narwhal_worker_address: Multiaddr("/dns/ewr-suival-a4bdd.devnet.sui.io/udp/8082"), voting_power: 2500, hostname: "validator-2" }, EpochStartValidatorInfoV1 { sui_address: 0xaef45505dd43de50dfedb965e28a28f904dfee5cdb82fb73967dade3bfa02529, protocol_pubkey: kRFoPTlvgJhYyiLIUed7qlUnbgjzp42RMKXns0tVwQq0HsxkwM+a8qAn6dd/XmC8FUAKmPHmyzaYEaE3oYnssok64ZcPKWtKNWDkTBqLcu6zICc1U9DHGFmNjmTn4K6T, narwhal_network_pubkey: nQvZpEpEuNVnWa+TgvSZJLztJNWjVDvEmY6peMxkcew=, narwhal_worker_pubkey: iTktmfh7ytu3dzW6uvHG55+Y7hVwBYRo4qBmdM7QWuE=, sui_net_address: Multiaddr("/dns/ewr-suival-db83g.devnet.sui.io/tcp/8080/http"), p2p_address: Multiaddr("/dns/ewr-suival-db83g.devnet.sui.io/udp/8084"), narwhal_primary_address: Multiaddr("/dns/ewr-suival-db83g.devnet.sui.io/udp/8081"), narwhal_worker_address: Multiaddr("/dns/ewr-suival-db83g.devnet.sui.io/udp/8082"), voting_power: 2500, hostname: "validator-3" }, EpochStartValidatorInfoV1 { sui_address: 0xeda56a3ff2d92185daa45763cde59e8e4a0a90a022203f178ea18124e2f8f582, protocol_pubkey: rKRYlG9KZEqVZNoam5D8IuNgpq5T5XugIOHHcdeG2vCANFHnKDwbwwVqK42foisMFnMCDDeF8d6weCfwI4bVDsI3/XiRdMZ8wH3KFflq7ZSnIqXKAnAxwdEQZN0Hb9XR, narwhal_network_pubkey: PTMuHLbOD/8fVfld4OY1yYEZ7eXMkY3RD9ZMfOfWG18=, narwhal_worker_pubkey: 3vV7JFzg2u0C2P50HFA7MNoilkM8RVaDG1rM6paaqNE=, sui_net_address: Multiaddr("/dns/ewr-suival-fdc33.devnet.sui.io/tcp/8080/http"), p2p_address: Multiaddr("/dns/ewr-suival-fdc33.devnet.sui.io/udp/8084"), narwhal_primary_address: Multiaddr("/dns/ewr-suival-fdc33.devnet.sui.io/udp/8081"), narwhal_worker_address: Multiaddr("/dns/ewr-suival-fdc33.devnet.sui.io/udp/8082"), voting_power: 2500, hostname: "validator-0" }, EpochStartValidatorInfoV1 { sui_address: 0xe969767df7dff095a395e770bdb1ebc6c316aeb7775b359681dd61e1a7bbfa55, protocol_pubkey: tyqOM8IwQ0HWKvWaq16AdgEEPzDW/gPryybMU2KjC2owIggJcv4WVIprNXJimNApExEgHX/mjYHcQVSeNgCrSZQw/ra0vGU9uzC72uK7FAgqJzkTXS31rQXscr2cOoNf, narwhal_network_pubkey: hhW0xe/pvUalvDyTdZFiBUoy8HOBHTtranUsEY1rHKQ=, narwhal_worker_pubkey: Sumkhtz2RbQtKV0hJbfZefeVUmjD6AH7Cs2qYExycVI=, sui_net_address: Multiaddr("/dns/ewr-suival-36163.devnet.sui.io/tcp/8080/http"), p2p_address: Multiaddr("/dns/ewr-suival-36163.devnet.sui.io/udp/8084"), narwhal_primary_address: Multiaddr("/dns/ewr-suival-36163.devnet.sui.io/udp/8081"), narwhal_worker_address: Multiaddr("/dns/ewr-suival-36163.devnet.sui.io/udp/8082"), voting_power: 2500, hostname: "validator-1" }] }), epoch_digest: CheckpointDigest(AMZ4QDCCQGZmnQBj7Vi4Y1h3nJZeQH6bFwJadXZ166rH), flags: [InMemoryCheckpointRoots] })
2023-10-02 14:15:39 fullnode-fullnode-1  | 2023-10-02T11:15:39.748509Z  INFO sui_core::authority::authority_store: Cur epoch: 0
2023-10-02 14:15:40 fullnode-fullnode-1  | thread 'sui-node-runtime' panicked at 'ProtocolVersion(26)', crates/sui-protocol-config/src/lib.rs:743:9
2023-10-02 14:15:40 fullnode-fullnode-1  | stack backtrace:
2023-10-02 14:15:40 fullnode-fullnode-1  | 2023-10-02T11:15:40.393780Z ERROR telemetry_subscribers: panicked at 'ProtocolVersion(26)', crates/sui-protocol-config/src/lib.rs:743:9 panic.file="crates/sui-protocol-config/src/lib.rs" panic.line=743 panic.column=9
2023-10-02 14:15:40 fullnode-fullnode-1  |    0:     0x5574d9ed24ba - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::he1c117e52d53614f
2023-10-02 14:15:40 fullnode-fullnode-1  |    1:     0x5574d9efcd9e - core::fmt::write::h25eb51b9526b8e0c
2023-10-02 14:15:40 fullnode-fullnode-1  |    2:     0x5574d9ecb775 - std::io::Write::write_fmt::ha9edec5fb1621933
2023-10-02 14:15:40 fullnode-fullnode-1  |    3:     0x5574d9ed2285 - std::sys_common::backtrace::print::h41b9b18ed86f86bd
2023-10-02 14:15:40 fullnode-fullnode-1  |    4:     0x5574d9ed3d1f - std::panicking::default_hook::{{closure}}::h22a91871f4454152
2023-10-02 14:15:40 fullnode-fullnode-1  |    5:     0x5574d9ed3a5b - std::panicking::default_hook::h21ddc36de0cd4ae7
2023-10-02 14:15:40 fullnode-fullnode-1  |    6:     0x5574d871200c - telemetry_subscribers::set_panic_hook::{{closure}}::he78e44bd0370e7c5
2023-10-02 14:15:40 fullnode-fullnode-1  |    7:     0x5574d9ed444a - std::panicking::rust_panic_with_hook::h5059419d6d59b3d0
2023-10-02 14:15:40 fullnode-fullnode-1  |    8:     0x5574d9ed41c9 - std::panicking::begin_panic_handler::{{closure}}::h0f383c291cd78343
2023-10-02 14:15:40 fullnode-fullnode-1  |    9:     0x5574d9ed296c - std::sys_common::backtrace::__rust_end_short_backtrace::h70ab22f2ad318cdd
2023-10-02 14:15:40 fullnode-fullnode-1  |   10:     0x5574d9ed3ed2 - rust_begin_unwind
2023-10-02 14:15:40 fullnode-fullnode-1  |   11:     0x5574d7868893 - core::panicking::panic_fmt::hd1d46bcde3c61d72
2023-10-02 14:15:40 fullnode-fullnode-1  |   12:     0x5574d932d18c - sui_protocol_config::ProtocolConfig::get_for_version::h914f1a87cae57588
2023-10-02 14:15:40 fullnode-fullnode-1  |   13:     0x5574d8658fe8 - sui_core::authority::authority_per_epoch_store::AuthorityPerEpochStore::new::hab4a1ee3fe9184e5
2023-10-02 14:15:40 fullnode-fullnode-1  |   14:     0x5574d7e32856 - sui_node::SuiNode::start_async::{{closure}}::h446778dab1249a68
2023-10-02 14:15:40 fullnode-fullnode-1  |   15:     0x5574d7e5d152 - sui_node::main::{{closure}}::haa8fd0eddbf3ca85
2023-10-02 14:15:40 fullnode-fullnode-1  |   16:     0x5574d7ddda25 - tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut::h050c2463ee61b816
2023-10-02 14:15:40 fullnode-fullnode-1  |   17:     0x5574d7c8b5cc - tokio::runtime::task::harness::Harness<T,S>::poll::h1ee8363ff328ddc4
2023-10-02 14:15:40 fullnode-fullnode-1  |   18:     0x5574d9dc6bcc - tokio::runtime::scheduler::multi_thread::worker::Context::run_task::hc91f8b758a9f8e7d
2023-10-02 14:15:40 fullnode-fullnode-1  |   19:     0x5574d9dc635e - tokio::runtime::scheduler::multi_thread::worker::Context::run::hb [...]

2023-10-02 23:49 UTC, mwtian commented
Looks like you are actually using an older version of the docker image. Make sure you have updated the `image` field in `docker-compose.yaml` to use the tag of the new image you built. You can take a look at the `Test Plan` section of the PR.

2023-10-03 21:07 UTC, teohaik commented
yeap it worked!

2023-10-03 21:09 UTC, teohaik approved these changes

2023-10-03 22:31 UTC, merged