[Wallet]: fix comments
MystenLabs/sui pull request #14076
Opened 2023-10-03 18:24 UTC by plam-ml

## Description 

- Fixing comments from https://github.com/MystenLabs/sui/pull/14059 and https://github.com/MystenLabs/sui/pull/14007

## Test Plan 

How did you test the new or updated feature?

---
If your changes are not user-facing and not a breaking change, you can skip the following section. Otherwise, please indicate what changed, and then add to the Release Notes section as highlighted during the release process.

### Type of Change (Check all that apply)

- [ ] protocol change
- [ ] user-visible impact
- [ ] breaking change for a client SDKs
- [ ] breaking change for FNs (FN binary must upgrade)
- [ ] breaking change for validators or node operators (must upgrade binaries)
- [ ] breaking change for on-chain data layout
- [ ] necessitate either a data wipe or data migration

### Release notes

2023-10-03 22:25 UTC, Jordan-Mysten requested changes
We're missing a resolution on these comments, either here as fixes, or on the originals PRs as explanations:

- https://github.com/MystenLabs/sui/pull/14059#discussion_r1343514148
- https://github.com/MystenLabs/sui/pull/14059#discussion_r1343514644
- https://github.com/MystenLabs/sui/pull/14007#discussion_r1343526222
- https://github.com/MystenLabs/sui/pull/14007#discussion_r1343525502
- https://github.com/MystenLabs/sui/pull/14007#discussion_r1343522841
- https://github.com/MystenLabs/sui/pull/14007#discussion_r1343521901
- https://github.com/MystenLabs/sui/pull/14007#discussion_r1343525208

2023-10-03 22:25 UTC, Jordan-Mysten commented on apps/wallet/src/ui/app/pages/home/tokens/TokensDetails.tsx
> +								copy="Send"
`copy` should be `children`

2023-10-04 00:26 UTC, plam-ml commented
https://github.com/MystenLabs/sui/pull/14007#discussion_r1343526222

This is because there is not a pool for `USDC > USDC`, it is assumed to be `1` so we can return early

2023-10-04 10:44 UTC, pchrysochoidis approved these changes

2023-10-04 16:23 UTC, plam-ml commented
Putting left-over concerns on this ticket so it does not block this merge

2023-10-05 00:14 UTC, merged