Fixed the code so that the example code works properly
MystenLabs/sui pull request #15005
Opened 2023-11-23 06:23 UTC by phanker

1. nft objects want image_url to display image information properly, not img_url.
2. should be using transfer::publish_transfer method instead of directly using transfer(object,sender).
3. Improve the mint method to make the contract mint capable

2023-11-28 18:22 UTC, damirka approved these changes

2023-11-28 18:22 UTC, damirka commented on docs/content/standards/display.mdx
> +        transfer::public_transfer(hero, sender(ctx));
I wouldn't change this signature. This is how we do things today - return so the sender can decide whether to transfer or not.

2023-11-28 18:23 UTC, damirka requested changes
Requesting changes to make sure the 'mint' function signature is not touched.

2023-11-29 01:22 UTC, phanker commented
> Requesting changes to make sure the 'mint' function signature is not touched.

I agree with this, I just made a regression of the mint function. But I don't think it's too beginner friendly, because this 'mint' method allows anyone to call it, and I believe it's intended to mint a nft to its own account, not only create, or transfer

2023-11-29 07:44 UTC, damirka approved these changes

2023-11-29 07:44 UTC, damirka commented
Thank you for this!

2023-11-29 19:20 UTC, merged

2023-11-29 19:20 UTC, stefan-mysten commented
Thanks @phanker for the PR!