Including brew tap instructions
MystenLabs/sui pull request #15191
Opened 2023-12-04 18:18 UTC by ronny-mysten

## Description 

Describe the changes or additions included in this PR.

## Test Plan 

How did you test the new or updated feature?

---
If your changes are not user-facing and not a breaking change, you can skip the following section. Otherwise, please indicate what changed, and then add to the Release Notes section as highlighted during the release process.

### Type of Change (Check all that apply)

- [ ] protocol change
- [ ] user-visible impact
- [ ] breaking change for a client SDKs
- [ ] breaking change for FNs (FN binary must upgrade)
- [ ] breaking change for validators or node operators (must upgrade binaries)
- [ ] breaking change for on-chain data layout
- [ ] necessitate either a data wipe or data migration

### Release notes

2023-12-04 18:23 UTC, stefan-mysten commented on docs/content/guides/developer/getting-started/sui-install.mdx
> +To confirm that Sui installed correctly, type `sui` and press Enter. You should see a message about the Sui version installed and help for using Sui commands.
Nit: whitespace added at the end.

2023-12-04 18:25 UTC, stefan-mysten requested changes
I would recommend we put `Homebrew complete install` first thing on the top page, before install from binaries. It is buried too deep down.

2023-12-04 18:26 UTC, ronny-mysten commented on docs/content/guides/developer/getting-started/sui-install.mdx
> +You can install Sui along with prequisites using the following commands.
```suggestion
You can install Sui along with prerequisites using the following commands.
```

2023-12-04 18:27 UTC, ronny-mysten commented on docs/content/guides/developer/getting-started/sui-install.mdx
> +To confirm that Sui installed correctly, type `sui` and press Enter. You should see a message about the Sui version installed and help for using Sui commands.
```suggestion
To confirm that Sui installed correctly, type `sui` and press Enter. You should see a message about the Sui version installed and help for using Sui commands.
```

2023-12-04 18:51 UTC, ronny-mysten commented
> Thanks for the super sonic fast update to this :D I would recommend we put `Homebrew complete install` first thing on the top page, before install from binaries. It is buried too deep down.

Not that fast as I had already created the content when the idea was made :) And the problem with putting that high up is that it's only for Mac users. Would also necessitate bringing up the Homebrew install info. Would also mess up the tabbed structure of the instructions.

2023-12-04 18:57 UTC, stefan-mysten commented
> > Thanks for the super sonic fast update to this :D I would recommend we put `Homebrew complete install` first thing on the top page, before install from binaries. It is buried too deep down.
> 
> Not that fast as I had already created the content when the idea was made :) And the problem with putting that high up is that it's only for Mac users. Would also necessitate bringing up the Homebrew install info. Would also mess up the tabbed structure of the instructions.

Homebrew can be used also on Linux and Windows, though I have not tried it. Ultimately feel free to decide what's best, but if as a user I have to scroll down through a long page to get to this two line command to install Sui, that's not a great user experience. I still vote for it being on the top, before installing via binaries.
```
# Homebrew install (including all prerequisites)
brew tap mystenlabs/tap
brew install mystenlabs/tap/sui
```

2023-12-04 18:57 UTC, stefan-mysten approved these changes

2023-12-05 04:40 UTC, johnjmartin reviewed
Agreed with @stefan-mysten on putting the homebrew install first on the list. It is just much less work to install than the other options, and it's really easy to filter out if you choose not to install via homebrew

2023-12-05 04:40 UTC, johnjmartin approved these changes

2023-12-11 16:52 UTC, merged

2023-12-11 17:52 UTC, stefan-mysten commented
Thanks @ronny-mysten !!!