Update explorer for new RPC data model
MystenLabs/sui pull request #1547
Opened 2022-04-22 22:14 UTC by stella3d

Not only has the way we fetch the data changed (we have a proper TS sdk now), the data we have available has changed due to network updates.

This means some of the pages needed changes to accommodate the new data.

things this includes:
* `TransactionResult` fetching (including from static)
* search utility now searches for transactions by digest
* updates for `ObjectResult` - mostly for the new data model, but some changes are also just to increase readability of the render function.
* updates for `AddressResult`

this doesn't include:
* the recent transactions list, as @Jibz1 is handling that.
* a rework of the mock data (which we should do, i just wanted to get this up ASAP)

I think there's likely some bugs in this due React misunderstanding, so i'm looking to the frontend experts to call out if i've accidentally broken anything

2022-04-22 22:54 UTC, todd-mystenlabs commented
Looks like a bunch of sui.js errors in in the Explorer Client PR checks step.

2022-04-23 07:32 UTC, 666lcz reviewed
Thanks for working on this! Since this includes UI changes, could you add screenshots for the transaction, object_info, and addresses page after your change if you don't mind? This will help reviewers have a better understanding on the effects of change without needing to run the code.

2022-04-23 07:32 UTC, 666lcz commented on explorer/client/src/components/ownedobjects/OwnedObjects.tsx
> +                        display: processDisplayValue(obj['display'] as string),
Hmm I don't think these are the fields you will receive from `getObjectInfo` . I got these when calling `GetObjectInfo` for `Coin<Sui>`

```
{
    "jsonrpc": "2.0",
    "result": {
        "status": "Exists",
        "details": {
            "objectRef": {
                "objectId": "8dc6a6f70564e29a01c7293a9c03818fda2d049f",
                "version": 2,
                "digest": "2PfMhH8NlP5eG1rq+NokUASK8HovA1PRlgmksm0QAcQ="
            },
            "object": {
                "contents": {
                    "fields": {
                        "id": {
                            "fields": {
                                "id": {
                                    "fields": {
                                        "id": {
                                            "fields": {
                                                "bytes": "8dc6a6f70564e29a01c7293a9c03818fda2d049f"
                                            },
                                            "type": "0x2::ID::ID"
                                        }
                                    },
                                    "type": "0x2::ID::UniqueID"
                                },
                                "version": 2
                            },
                            "type": "0x2::ID::VersionedID"
                        },
                        "value": 99873
                    },
                    "type": "0x2::Coin::Coin<0x2::SUI::SUI>"
                },
                "owner": {
                    "AddressOwner": "c5206dd02c86a510c4848516229b02addfacbe55"
                },
                "tx_digest": "Zb51CbtIKEbzvwjSRyFoMTVQCo3hG8rjy9vnFEGP4X0="
            }
        }
    },
    "id": 1
}
```

2022-04-23 07:32 UTC, 666lcz commented on explorer/client/src/components/ownedobjects/OwnedObjects.tsx
> +                    return {
nit: I would add a status field to signify the object is deleted or not exists, so that the front end can render them differently.

2022-04-23 07:32 UTC, 666lcz commented on explorer/client/src/pages/transaction-result/TransactionResult.tsx
>  function TransactionResult() {
This function is way too long and there are more logic to be added here, can we make it shorter by having a few more smaller functions/components?

2022-04-23 07:32 UTC, 666lcz commented on explorer/client/src/pages/object-result/ObjectResultType.tsx
> +export type ObjectResult = {
Where do these fields come from?

2022-04-25 10:43 UTC, Andrew47 requested changes
## Problems
* `yarn test` now fails and the static version of the website no longer displays data for the objects detailed in `explorer/client/src/utils/static/mock_data.json`.
* Without some example objects for which we expect the `api` version of the website to work, it is unclear whether the website interacts with the TypeScript SDK.
* The Geniteam API (https://demo-rpc.sui.io/) still follows the REST API and so, if this code branch were deployed to the live website ((https://explorer-demo.sui.io/), the website would no longer work. 

## Potential Solution

We need a matching up between the local API delivered by the TypeScript SDK, the internet API delivered by the Geniteam API and the data expected by the SuiExplorer website (encapsulated by the `mock_data.json` file).

## Implementation

* The TypeScript SDK needs documentation that details:
    - How to spin up a server
    - Example commands that give object and address results
    
* The static JSON can then be updated to reflect the new data model delivered by the TypeScript SDK and the UI updated such that the e2e tests pass.

* The Geniteam API and SuiExplorer Website can then be redeployed with the new RPC model.

2022-04-25 16:51 UTC, Andrew47 commented on explorer/client/src/pages/object-result/ObjectResult.tsx
> +function instanceOfDataType(object: any): object is GetObjectInfoResponse {
This is causing the version of the SuiExplorer website based on static `mock_data.json` to display errors for all objects. This is part of the reason why `yarn test` fails. The static objects will need to be updated to follow the schema implied by `isGetObjectInfoResponse`.

2022-04-27 21:07 UTC, todd-mystenlabs commented
Hey all! I think we need this to make it in.  What is the MVP for getting this one checked in?  (i.e. Nits and all, whatever is mandatory to fix, fine, but lets not block everyone at this point.)

2022-04-28 03:24 UTC, 666lcz commented on explorer/client/src/pages/transaction-result/TransactionResult.tsx
> +    if (isCertifiedTransaction(showTxState)) {
This is not a good pattern. The data validation already happens at the SDK level, so we should not need to check again here. If `data.loadState == 'loaded'`, you can then safely assume that `txState` is `CertifiedTransaction`

2022-04-28 16:54 UTC, Andrew47 commented
# Proposal for Manually Testing the SuiExplorer Website's Connection with the RPC API

Note: this is a copy and paste from the Slack message

After much discussion with @Chris Li as well as testing locally, the below seems to be a way to manually test whether the SuiExplorer is correctly connected to the RPC API in PR 1547 (https://github.com/MystenLabs/sui/pull/1547):

* `cd` to `sdk/typescript` and run `yarn && yarn build && npm link`
* `cd` to `explorer/client`
* Change the URL to http://34.105.36.61:9000/ in line 14 of `src/utils/api/DefaultRpcClient.ts`
* Run `npm link sui.js && yarn && yarn start`
* Open the browser on http://localhost:3000
* Search for an object or address. At the time of this post, `e7d50aa63733d21cecbf9a7cf89f9adb7212a3da` is an object that exists and so can be used for testing. 

Unfortunately, this testing framework suggests that PR 1547 does not correctly connect the SuiExplorer UI to the RPC API. Searching for `e7d50...` leads to a blank screen and errors:

![image](https://user-images.githubusercontent.com/11377188/165804481-d5b1349e-5dc9-429e-8b6f-f57bfe578194.png)

# Next Steps

* @todd-mystenlabs --> In terms of the MVP for getting this PR checked in, it looks reasonable to say a PR where the above manual check does not generate obvious errors.
* @stella3d --> Will this guide be sufficient to get the PR into a working state?
* @666lcz  --> Is there stability in e7d50... being suitable for testing the SuiExplorer website?

2022-06-11 01:03 UTC, closed without merging