[Move] Fixed test function calling entry functino and updated docs
MystenLabs/sui pull request #1653
Opened 2022-04-28 17:12 UTC by awelc

Introduction of `public(script)` designation of entry points introduced a requirement to put the same modifier on the test functions calling entry functions. This fixes the problem for the Move quick start tutorial.

2022-04-28 17:43 UTC, Clay-Mysten approved these changes
Thanks, Adam!

2022-04-28 21:47 UTC, lxfind commented on doc/src/build/move.md
>  - have parameters ordered as follows:
This seems out of dated too.

2022-05-10 21:26 UTC, lxfind requested changes
Could we update this and merge it soon? This part seems still out-of-dated.

2022-05-11 17:50 UTC, lxfind approved these changes

2022-05-11 17:50 UTC, merged