[move-ide] Improve code build times in the IDE
MystenLabs/sui pull request #16555
Opened 2024-03-06 22:55 UTC by awelc

## Description 

Source code build times in the IDE, while quite fast, causes a noticeable difference between re-build trigger (e.g., modification in the file) and re-build finish (e.g., when the user observes the build diagnostics).

This PR mitigates this problem in two ways:
- elides compilation of files in `tests` and `examples` directories of the root package dependencies
- elides saving files to disk at the end of compilation (as in the IDE it's the side-effects of the compilation that matter)

Note that `tests` and `examples` directories are not included "by default" but if they are actually opened in the IDE for inspection, the compilation for those will actually happen and symbols for them will be computed and available.

## Test Plan 

Verified that build times drop by more than 50% when including Move stdlib and Sui framework code as dependencies.

2024-03-07 22:25 UTC, tnowacki requested changes
Not the biggest fan of this bandaid, though I don't have an issue with an IDE flag conceptually. 

I would prefer for us to solve this in the compiler by reworking the whole "is_dependency" thing, so we wouldn't have to compile the bodies of deps for the IDE, which is going to save more time than just skipping tests

2024-03-08 00:35 UTC, awelc commented
> Not the biggest fan of this bandaid, though I don't have an issue with an IDE flag conceptually.
> 
> I would prefer for us to solve this in the compiler by reworking the whole "is_dependency" thing, so we wouldn't have to compile the bodies of deps for the IDE, which is going to save more time than just skipping tests

Avoiding to compile bodies for deps for IDE has about the same effect timewise as the original bandaid (no bodies: ~0.5s => ~0.19s vs. no tests/examples: ~0.5s => ~0.21s), but together they are a real bomb (~0.5s > ~0.9s) so it would be great to be able to keep both... :-)

2024-03-08 01:20 UTC, awelc commented
This version only keeps the idea of skipping compilation of function bodies for deps by simply re-using the existing machinery.

2024-03-13 21:55 UTC, awelc commented
Superseded by https://github.com/MystenLabs/sui/pull/16580

2024-03-13 21:55 UTC, closed without merging