[suiop] allow specifying CPU/RAM/DISK requests and build args
MystenLabs/sui pull request #18472
Opened 2024-06-30 21:17 UTC by pei-mysten

## Description 

after adding the support for specifying hardware request in infra-metadata-servcie, we could now allow this from suiop CLI as well.

## Test plan 

How did you test the new or updated feature?

---

## Release notes

Check each box that your changes affect. If none of the boxes relate to your changes, release notes aren't required.

For each box you select, include information after the relevant heading that describes the impact of your changes that a user might notice and any actions they must take to implement updates. 

- [ ] Protocol: 
- [ ] Nodes (Validators and Full nodes): 
- [ ] Indexer: 
- [ ] JSON-RPC: 
- [ ] GraphQL: 
- [ ] CLI: 
- [ ] Rust SDK:

2024-07-02 13:14 UTC, after-ephemera commented
I almost would prefer predefined settings, e.g. `--size-small`, `--heavyduty`, or `--beast-mode` so we don't have to calculate cpu/memory/disk reqs every time. @pei-mysten what do you think?

2024-07-02 13:15 UTC, after-ephemera requested changes
more discussion before approving!

2024-07-03 20:06 UTC, pei-mysten commented
> I almost would prefer predefined settings, e.g. `--size-small`, `--heavyduty`, or `--beast-mode` so we don't have to calculate cpu/memory/disk reqs every time. @pei-mysten what do you think?

sounds brilliant! i'll make a new flag `--mode` which has a preset value of `cpu/ram/disk` for `small/heavy/beast` while allowing users to customize if they really need to

2024-07-03 22:15 UTC, after-ephemera approved these changes
love it

2024-07-03 22:27 UTC, merged