sdk: add passkey recovery option
MystenLabs/sui pull request #20722
Opened 2024-12-23 18:31 UTC by joyqvq

## Description 

after thinking about https://github.com/MystenLabs/passkey-example?tab=readme-ov-file#notes-on-wallet-storage i realize we should provide the recovery ability in our sdk since getPasskeyInstance is a bit unflexible and create a new credential every time when called. we should allow user to find its passkey wallet without creating a new one. similar to "log in to existing" vs "create new". but i leave the way to recover to the wallet impelementer due to the ux considerations. one requires two signings and the other requires one. 

## Test plan 

How did you test the new or updated feature?

---

## Release notes

Check each box that your changes affect. If none of the boxes relate to your changes, release notes aren't required.

For each box you select, include information after the relevant heading that describes the impact of your changes that a user might notice and any actions they must take to implement updates. 

- [ ] Protocol: 
- [ ] Nodes (Validators and Full nodes): 
- [ ] gRPC:
- [ ] JSON-RPC: 
- [ ] GraphQL: 
- [ ] CLI: 
- [ ] Rust SDK:

2025-01-08 19:31 UTC, hayes-mysten commented on sdk/typescript/src/keypairs/passkey/keypair.ts
> +	constructor(provider: PasskeyProvider, publicKey?: Uint8Array) {
Not sure who is using this so far, but this is a breaking change

2025-01-08 19:37 UTC, hayes-mysten commented on sdk/typescript/src/keypairs/passkey/keypair.ts
> +	 * const uniquePk = findUniquePublicKey(possiblePks, possiblePks2);
unique seems backwards here, you want the non-unique key right?  We can probably add an actual implementation like `possiblePks.find(pk => !!possiblePks2.find(pk2 => pk.equals(pk2))`

2025-01-08 19:38 UTC, hayes-mysten commented on sdk/typescript/src/keypairs/passkey/keypair.ts
> +	 * const uniquePk = findUniquePublicKey(possiblePks, possiblePks2);
ah, didn't see we actually implemented this below

2025-01-08 19:39 UTC, hayes-mysten commented on sdk/typescript/src/keypairs/passkey/keypair.ts
> +export function findUniquePublicKey(arr1: PublicKey[], arr2: PublicKey[]): PublicKey {
same comment as above, unique seems like the wrong term here.

2025-01-08 19:44 UTC, hayes-mysten commented on sdk/typescript/src/keypairs/passkey/keypair.ts
> +	private publicKey?: Uint8Array;
I can't figure out why we want to change this.  We are asserting that this is set everywhere its used, and I don't see any examples of constructing a `PasskeyKeypair` without a publicKey

2025-01-09 21:40 UTC, joyqvq commented on sdk/typescript/src/keypairs/passkey/keypair.ts
> +	private publicKey?: Uint8Array;
you are right! it was somehow in my previous iteration on this. reverted.

2025-01-09 21:40 UTC, joyqvq commented on sdk/typescript/src/keypairs/passkey/keypair.ts
> +	constructor(provider: PasskeyProvider, publicKey?: Uint8Array) {
removed!

2025-01-09 21:58 UTC, hayes-mysten commented on sdk/typescript/src/keypairs/passkey/keypair.ts
> +	 * const uniquePk = findUniquePublicKey(possiblePks, possiblePks2);
the code is finding the matching keys from the 2 lists, which is the opposite of unique

2025-01-09 21:59 UTC, hayes-mysten commented on sdk/typescript/src/keypairs/passkey/keypair.ts
> +		arr.set(this.publicKey!, 1 + normalized.length);
this assertion shouldn't be needed anymore

2025-01-09 21:59 UTC, hayes-mysten commented on sdk/typescript/src/keypairs/passkey/keypair.ts
> +			this.publicKey!.length !== PASSKEY_PUBLIC_KEY_SIZE
not needed anymore

2025-01-09 21:59 UTC, hayes-mysten requested changes
This PR will need to be ported over to https://github.com/mystenLabs/ts-sdks

2025-01-09 22:01 UTC, joyqvq commented on sdk/typescript/src/keypairs/passkey/keypair.ts
> +	 * const uniquePk = findUniquePublicKey(possiblePks, possiblePks2);
ah i see where the confusion is, i meant to say there should be exactly one common key that exists in both list. 
what about `findCommonPublicKey` ?

2025-01-09 22:02 UTC, hayes-mysten commented on sdk/typescript/src/keypairs/passkey/keypair.ts
> +	 * const uniquePk = findUniquePublicKey(possiblePks, possiblePks2);
that sounds good to me!

2025-01-10 14:28 UTC, joyqvq commented
closed in favor of pr in ts-sdks!

2025-01-10 14:28 UTC, closed without merging