[framework] vector zip destroy_empty + allow return values in lambdas
MystenLabs/sui pull request #20745
Opened 2024-12-27 17:54 UTC by damirka

## Description 

- adds `v2.destroy_empty` in `zip_do` to support destroying vectors of non-droppable `T`s 
- allows return value in lambdas as a convenience feature to not wrap lambdas into braces

## Test plan 

- features tests

---

## Release notes

Check each box that your changes affect. If none of the boxes relate to your changes, release notes aren't required.

For each box you select, include information after the relevant heading that describes the impact of your changes that a user might notice and any actions they must take to implement updates. 

- [ ] Protocol: 
- [ ] Nodes (Validators and Full nodes): 
- [ ] gRPC:
- [ ] JSON-RPC: 
- [ ] GraphQL: 
- [ ] CLI: 
- [ ] Rust SDK:

2025-01-06 21:38 UTC, tnowacki commented on crates/sui-framework/packages/move-stdlib/sources/macros.move
> +public macro fun range_do($start: _, $stop: _, $f: |_| -> _) {
These changes feel fine to me, I just wonder if it is worth annotating, e.g. 
```suggestion
public macro fun range_do<R: drop>($start: _, $stop: _, $f: |_| -> R) {
```
Perhaps @tzakian or @cgswords will have opinions

2025-01-16 08:45 UTC, damirka commented on crates/sui-framework/packages/move-stdlib/sources/macros.move
> +public macro fun range_do($start: _, $stop: _, $f: |_| -> _) {
Wouldn't it force the return value to exist? Or `R: drop` can be `()`?

2025-01-16 16:19 UTC, tnowacki commented on crates/sui-framework/packages/move-stdlib/sources/macros.move
> +public macro fun range_do($start: _, $stop: _, $f: |_| -> _) {
It can be `()` for macros. Generics for macros have `$` for that reason to indicate they are a bit different, (so my suggestion should be)
```suggestion
public macro fun range_do<$R: drop>($start: _, $stop: _, $f: |_| -> $R) {
```

2025-01-16 20:13 UTC, cgswords commented on crates/sui-framework/packages/move-stdlib/sources/macros.move
> +public macro fun range_do($start: _, $stop: _, $f: |_| -> _) {
Agreed this should have `drop` to help indicate the intended outcome to the programmer.

2025-01-17 06:50 UTC, damirka commented
Addressed your comment @tnowacki, let me know if you want a similar approach elsewhere in the code.

2025-01-23 19:41 UTC, tnowacki commented on crates/sui-framework/packages/move-stdlib/sources/macros.move
> +public macro fun range_do($start: _, $stop: _, $f: |_| -> _) {
Can we not do `$R: drop` for these macros? Or do we not care since they are helpers? 
Or do we not care since we don't annotate the other types?

2025-01-23 19:54 UTC, damirka commented on crates/sui-framework/packages/move-stdlib/sources/macros.move
> +public macro fun range_do($start: _, $stop: _, $f: |_| -> _) {
@tnowacki I suggest we do all integer ones in a follow up. They won't be making any bytecode changes so should be an easy land.

2025-01-23 19:55 UTC, damirka commented on crates/sui-framework/packages/move-stdlib/sources/macros.move
> +public macro fun range_do($start: _, $stop: _, $f: |_| -> _) {
Gonna be a relatively big change.

2025-01-23 19:56 UTC, damirka commented on crates/sui-framework/packages/move-stdlib/sources/macros.move
> +public macro fun range_do($start: _, $stop: _, $f: |_| -> _) {
Nvm. I'll add it here since I already started.

2025-01-23 20:10 UTC, tnowacki approved these changes

2025-01-23 20:10 UTC, tnowacki commented on crates/sui-framework/packages/move-stdlib/sources/macros.move
> +public macro fun range_do<$R: drop>($start: _, $stop: _, $f: |_| -> $R) {
I'm a bit torn, so my comment was more about starting a discussion than suggesting a particular direction. Mixing and matching _ and named generics feels a bit strange, but it doesn't really matter much for these since they are really just helpers. 
My point is `_` is neat, but it makes it harder to annotate types if you need to.

2025-01-23 20:13 UTC, tnowacki commented on crates/sui-framework/packages/move-stdlib/.prettierrc
> +{
Should this file be a separate PR?

2025-01-23 20:13 UTC, tnowacki commented on crates/sui-framework/packages/move-stdlib/.prettierrc
> +{
I just don't know what it is doing 🙃

2025-01-23 21:28 UTC, damirka commented on crates/sui-framework/packages/move-stdlib/sources/macros.move
> +public macro fun range_do<$R: drop>($start: _, $stop: _, $f: |_| -> $R) {
Personally I am focused on the practical issue which is regular annoyance when I have a return value in a lambda. As to whether to use `_` or `$R: drop` - no opinion, but I find `_` slightly less confusing, and when someone looks at the macros as they are implemented right now, they might feel obliged to add (or at least to think) about `$R`, whereas the `_` is less misleading to less experienced devs.

2025-01-23 21:28 UTC, damirka commented on crates/sui-framework/packages/move-stdlib/.prettierrc
> +{
Will do a separate!

2025-01-24 18:28 UTC, tnowacki requested changes
One sec, sorry. Having a crisis

2025-01-24 18:38 UTC, tzakian commented on crates/sui-framework/packages/move-stdlib/sources/macros.move
> +public macro fun range_do<$R: drop>($start: _, $stop: _, $f: |_| -> $R) {
IMO in this case I think `_` should really be a type parameter due to the "fixity" of the types needed for `$start` `$stop` and `f: |_| -> $R` in particular all the `_`'s must be the same type. Whereas `_` for all of them provides a looser type signature that is not always correct.

2025-01-24 18:55 UTC, tnowacki commented on crates/sui-framework/packages/move-stdlib/sources/macros.move
> +public macro fun range_do<$R: drop>($start: _, $stop: _, $f: |_| -> $R) {
Fair enough. 
Let's swap all the `_` for `$T`. 

I think we should avoid mixing and matching `_` and `$T`, so if we should use `$T` here, let's do it

2025-01-24 19:32 UTC, tnowacki commented on crates/sui-framework/packages/move-stdlib/sources/macros.move
> +public macro fun num_to_string<$T>($x: $T): String {
Let's revert this one. `$T` isn't shared

2025-01-24 19:32 UTC, tnowacki commented on crates/sui-framework/packages/move-stdlib/sources/macros.move
> +public macro fun try_as_u128<$T>($x: $T): Option<u128> {
Let's revert these

2025-01-24 21:01 UTC, tnowacki approved these changes

2025-01-24 21:56 UTC, ronny-mysten reviewed
helpful, i know

2025-01-24 21:56 UTC, ronny-mysten commented on crates/sui-framework/CONTRIBUTING.md
> +Run the following script from the Sui's [root directory](../../) and accept the changes, if any (if you do not have `cargo-insta` command installed, please run the `cargo install cargo-insta` command
```suggestion
Run the following script from the Sui's [root directory](../../) and accept any changes (if you do not have `cargo-insta` installed, run the `cargo install cargo-insta` command first):
```

2025-01-25 10:29 UTC, merged