Show address that publishes a package
MystenLabs/sui pull request #2704
Opened 2022-06-24 14:42 UTC by Jibz1

![Screen Shot 2022-06-24 at 10 35 24 AM](https://user-images.githubusercontent.com/8676844/175559137-892c8324-0523-45a2-8498-232a350a7433.png)

2022-06-24 14:45 UTC, bwann52 commented
I think calling it Publisher is more clear

2022-06-24 16:08 UTC, Andrew47 requested changes
Overall looks great and tests well across a variety of objects. Would appreciate feedback from @bwann52 on how we handle the Genesis case, otherwise good for merge.

2022-06-24 16:08 UTC, Andrew47 commented on explorer/client/src/pages/object-result/ObjectResult.tsx
> +                        // TODO: Not sure if I should show Genesis as Package Publisher or ignore it
I like the overall approach; it's efficient. 

Regarding packages such as 0x2 that exist at Genesis, perhaps the best approach would be to remove the row detailing the `Last Transaction ID` and input 'Genesis' as a string next to `Publisher`? Would this be a better approach, Bauer (@bwann52)? 

Below is a screenshot of what this PR delivers for package 0x2:

![image](https://user-images.githubusercontent.com/11377188/175573350-01580c03-d163-4646-8e71-338f6e198146.png)

Note that the blue Genesis text is clickable and will take you to the following error page:

![image](https://user-images.githubusercontent.com/11377188/175573529-2083de9c-9a1e-4205-bc19-84af06d04ca3.png)

A possible alternative would be the following, with no clickable link:
![image](https://user-images.githubusercontent.com/11377188/175574108-28e6928f-9fc1-4bad-91d0-561276d74737.png)

2022-06-24 16:38 UTC, Jibz1 commented
![Screen Shot 2022-06-24 at 12 37 45 PM](https://user-images.githubusercontent.com/8676844/175594438-37ed318f-8bcb-4d8e-8de2-26ac2ff78e47.png)

@Andrew47 done

2022-06-24 18:43 UTC, Andrew47 commented
> ![Screen Shot 2022-06-24 at 12 37 45 PM](https://user-images.githubusercontent.com/8676844/175594438-37ed318f-8bcb-4d8e-8de2-26ac2ff78e47.png)
> 
> @Andrew47 done

@Jibz1 --> Would it be possible to remove the Last Transaction ID row for Genesis?

2022-06-24 19:38 UTC, Jibz1 commented
![Screen Shot 2022-06-24 at 3 34 47 PM](https://user-images.githubusercontent.com/8676844/175656144-2515deb2-23d0-44d5-bbac-dc4274a0f7a0.png)

done

2022-06-27 10:09 UTC, Andrew47 approved these changes
Perfect - good to merge

2022-06-27 10:09 UTC, merged