Explorer transfer table1
MystenLabs/sui pull request #3101
Opened 2022-07-08 13:32 UTC by Jibz1

- Created Tabs and Table components that can be reused
- Update the home page to match the design using this component 
- Warning a lot of mock data in areas where we do not have it. We easily update or remove those components.
- update the timeUtil to include shorter displays

![Screen Shot 2022-07-08 at 10 07 55 AM](https://user-images.githubusercontent.com/8676844/178008733-9d2f8447-830a-4f5f-85f7-5eb1f19029e8.png)

https://user-images.githubusercontent.com/8676844/178000647-6e901401-0a40-4265-9f09-31023f565b45.mov

2022-07-08 15:11 UTC, stella3d requested changes
looks mostly good, i feel like this bundles together a few parts which should come separately.

We could really use this table view as a re-usable component for other kinds of data.  I would like it if we can break that out of the part of this PR that relies on mock data we don't have ready yet - would make it easier to review.

2022-07-08 15:17 UTC, Jibz1 commented on explorer/client/src/components/table/TableCard.tsx
> +// support multiple types with sepcial handling for 'addresses'/links and status
> sepcial -> special

Noted. 

Currently, the table view supports almost all input types. The `Links` and `Status` are just special cases with design support. 
![Screen Shot 2022-07-08 at 11 15 39 AM](https://user-images.githubusercontent.com/8676844/178021133-c86999ef-6a5a-4b22-892c-eafc81bda75a.png)

2022-07-08 16:21 UTC, Jibz1 commented on explorer/client/src/components/table/TableCard.tsx
> +function TableCard({
@stella3d this has been refactored. Please review.

2022-07-08 19:10 UTC, Jibz1 commented
![Screen Shot 2022-07-08 at 3 08 29 PM](https://user-images.githubusercontent.com/8676844/178055624-a3305bc6-0cd8-4f5d-b859-ccbd939dd0cd.png) @666lcz

2022-07-08 19:22 UTC, 666lcz commented on explorer/client/src/components/transaction-card/RecentTxCard.tsx
> +            alttext: 'More Transaction',
```suggestion
            alttext: 'More Transactions',
```

2022-07-11 15:49 UTC, 666lcz approved these changes

2022-07-11 17:23 UTC, Jibz1 commented on explorer/client/src/components/table/TableCard.tsx
> +// support multiple types with sepcial handling for 'addresses'/links and status
@stella3d this has been updated please review. Thanks

2022-07-11 17:53 UTC, stella3d approved these changes

2022-07-11 18:11 UTC, merged