[tutorial] add tictactoc publish script
MystenLabs/sui pull request #3540
Opened 2022-07-27 03:36 UTC by zhengxunWu1

Add a script for automating the process of publish the tictactoe game contract

2022-07-27 14:04 UTC, code-eren commented
hey @Clay-Mysten @randall-Mysten , very fresh newbie here, it's my first time contributing to this project, trying to get sernse of the contribution workflow, could you approve running it and gave some recommendations? bit confused on whether i am bumping the right version

2022-07-27 19:13 UTC, randall-Mysten commented
Hi @code-eren, thanks for your contribution. I will look into this (I am new myself) and follow up. We are actively working on updating the information about how to contribute to Sui. Thanks for your patience!

2022-07-27 21:12 UTC, tharbert commented
Hi @code-eren! Thanks a bunch for your work here. I won't comment on the tictactoe script right now however regarding the RELEASES and versioning changes, can you port or cherry-pick `ad6d37e32b557b7c27877839a38c67c886af7d2e` over from the devnet branch? This has the updates including the 0.6.2 release/version references. This is something I should have done myself yesterday during the deployment. Thanks again for contributing.

2022-07-27 21:56 UTC, code-eren commented
> Hi @code-eren! Thanks a bunch for your work here. I won't comment on the tictactoe script right now however regarding the RELEASES and versioning changes, can you port or cherry-pick `ad6d37e32b557b7c27877839a38c67c886af7d2e` over from the devnet branch? This has the updates including the 0.6.2 release/version references. This is something I should have done myself yesterday during the deployment. Thanks again for contributing.

Hi @tharbert, cherry-picked. I wonder whether you want this version bump landed in main with this pr, or I can just discard version changes to make it same as current main.

2022-07-27 22:10 UTC, randall-Mysten requested changes

2022-07-28 00:08 UTC, code-eren commented on doc/src/explore/tutorials.md
> +PLAYER_X=$CLIENT_ADDRESS | head -n 2
From my view, they seem use PLAYER_X and PLAYER_O? could you double check?

2022-07-28 02:04 UTC, code-eren commented on doc/src/explore/tutorials.md
> +PLAYER_X=$CLIENT_ADDRESS | head -n 2
updated

2022-07-28 14:14 UTC, tharbert commented
The releases/versioning looks good to me!

2022-07-28 15:52 UTC, randall-Mysten approved these changes

2022-07-28 15:52 UTC, randall-Mysten commented on doc/src/explore/tutorials.md
> +may be useful to save some time.
```suggestion
If you prefer not to enter command step by step, or need to go though it multiple
times (such as when you change some Move source code), the following automated script
may be useful to save some time.
```

2022-07-28 15:52 UTC, randall-Mysten commented on doc/src/explore/tutorials.md
> +may be useful to save some time.
if nothing else, please fix the extra space in `code )`

2022-07-28 20:54 UTC, randall-Mysten approved these changes

2022-07-29 15:33 UTC, randall-Mysten approved these changes
thanks for the additional commits, sorry for the issues with this

2022-07-30 20:09 UTC, merged

2022-08-01 16:23 UTC, Clay-Mysten commented
Interesting addition. Adding Xun, Adam, and Patrick retroactively as an FYI.

2022-08-01 16:23 UTC, Clay-Mysten commented
Also wondering whether we could employ this type of script elsewhere.

2022-08-01 16:29 UTC, randall-Mysten commented
Xun reviewed the script in Slack prior to merge, just as an FYI

2022-08-01 16:41 UTC, Clay-Mysten commented
> Xun reviewed the script in Slack prior to merge, just as an FYI

Ah, thanks Randall and Xun!

2022-08-02 18:57 UTC, Clay-Mysten commented
@code-eren , please note we will feature your excellent contribution in our AMA on tech writing tomorrow:
https://discord.com/channels/916379725201563759/925109817834631189/1003637556379910244

2022-08-02 18:57 UTC, Clay-Mysten commented
Please join us.