Update fullnode.md
MystenLabs/sui pull request #3797
Opened 2022-08-05 20:42 UTC by grossbel12

Ad chapter Typical issues. This section will show common problems and solutions for people who are not familiar with installing nodes and who are setting up a node for the first time. For instance, I add typical error 98/99.

2022-08-05 21:46 UTC, randall-Mysten reviewed
Thanks for submitting this contribution. A couple of questions for you.

2022-08-05 21:46 UTC, randall-Mysten commented on doc/src/build/fullnode.md
> +## Typical isues
```suggestion
## Resolving errors 
```

2022-08-05 21:46 UTC, randall-Mysten commented on doc/src/build/fullnode.md
> +1. Error 98/99  ![Error 98](https://user-images.githubusercontent.com/86624298/183159157-46971a06-a5c4-4196-80b0-63177a78164d.png)
```suggestion
#### Error 98/99
```

2022-08-05 21:46 UTC, randall-Mysten commented on doc/src/build/fullnode.md
> +    ```
```suggestion
If you receive an error with code 98 or 99, you should restart your server using the following command:
`$ shutdown -r now` 

Then, restart your Sui fullnode:
`$ cargo run --release --bin sui-node -- --config-path fullnode.yaml`
```

Is there an extra -- in the command?
--bin sui-node -- --config-path

2022-08-05 21:54 UTC, randall-Mysten commented
Hey folks, I am working with grossbel12 after some chatting in Discord. This is a trial run with a new user, thanks for your patience. We'll fix the branch etc.

2022-08-05 23:35 UTC, huitseeker requested changes
I think the PR could be better if it indicated 
1. The 98 error code is only valid in Linux, in windows it's a code 10048. 
2. The reason for the error is that one of the bind addresses used in the configuration is already in use on the system. 
3. Finding what other thing is using the port and managing who gets what resource is key to resolving this. There are many articles on the internet on how to dig into this, [e.g.](https://handsonnetworkprogramming.com/articles/bind-error-98-eaddrinuse-10048-wsaeaddrinuse-address-already-in-use/).
4. restarting the server is not the only nor necessarily the right solution. Rather the documentation should indicate: "as one of the ways to address this, you could restart your system, shutting down servers that might have been started on the system".

2022-08-09 16:04 UTC, Clay-Mysten commented
Thanks for the contribution @grossbel12 , coordination @randall-Mysten, and input @huitseeker. Randall, we can discuss how to improve this in our meeting today.

It would be good to have more than one issue. I wonder if @tharbert, @bmwill , @mystenmark , @allan-bailey or @ebmifa have other known fullnode issues we can include here too. Thanks, all.

2022-08-10 18:00 UTC, Clay-Mysten commented
Asking @bmwill to take a look.

2022-08-11 21:09 UTC, grossbel12 commented
I created new common error in my repositories, I send message to @randall-Mysten. If the topic with common problems with Fullnode is relevant, I'll add some.

2022-08-12 15:39 UTC, Clay-Mysten commented
> I created new common error in my repositorie, I send message to @randall-Mysten. If the topic with common problems with Fullnode is relevant, I'll add some.

Please include the common errors here. Thanks!

2022-08-12 17:00 UTC, grossbel12 commented
> > I created new common error in my repositorie, I send message to @randall-Mysten. If the topic with common problems with Fullnode is relevant, I'll add some.
> 
> Please include the common errors here. Thanks!

Done check plz

2022-08-12 17:35 UTC, randall-Mysten commented
> > > I created new common error in my repositorie, I send message to @randall-Mysten. If the topic with common problems with Fullnode is relevant, I'll add some.
> > 
> > 
> > Please include the common errors here. Thanks!
> 
> Done check plz

Thank you. I see some comments from huitseeker that are still pending. Do you want to try and address those?

2022-08-15 15:54 UTC, Clay-Mysten commented
> > > > I created new common error in my repositorie, I send message to @randall-Mysten. If the topic with common problems with Fullnode is relevant, I'll add some.
> > > 
> > > 
> > > Please include the common errors here. Thanks!
> > 
> > 
> > Done check plz
> 
> Thank you. I see some comments from huitseeker that are still pending. Do you want to try and address those?

Actually, this entire solution is covered in:
https://docs.sui.io/devnet/build/fullnode#built-from-source

So I agree with @huitseeker we should qualify the error with your environment as the new information here. Can you confirm your operating system and version? Also, please send a higher resolution version of the image as it is blurry at full size:
https://user-images.githubusercontent.com/86624298/184237312-4af31e15-c939-47e9-8055-535bee579dba.png

Thanks, @grossbel12 !

2022-09-22 18:33 UTC, randall-Mysten commented
I am closing this PR as it is stale and some of the issues are being addressed with other content updates. Please submit another PR if there are still unresolved issues. Thanks for contributing to Sui.

2022-09-22 18:33 UTC, closed without merging