[explorer] Migrate to new home page
MystenLabs/sui pull request #3857
Opened 2022-08-08 22:37 UTC by Jordan-Mysten

This migrates the `/home-other` route to the index route, and moves the transaction list to `/transactions`. This is in preparation of the release of the new explorer.

Screenshot:
<img width="1550" alt="Screen Shot 2022-08-08 at 3 35 35 PM" src="https://user-images.githubusercontent.com/109986297/183526347-f8483e9a-75cb-42ba-b681-80dda00630a7.png">

Depends on #3851 landing.

2022-08-08 22:40 UTC, Jibz1 approved these changes

2022-08-09 14:48 UTC, Andrew47 approved these changes
This looks correct. The remaining question is whether we want to deploy this with 4 validators or to wait.

2022-08-09 14:52 UTC, Andrew47 requested changes
Following on from Slack (@bwann52 / @666lcz ), the plan is to wait on merging this PR until the validator data is ready.

2022-08-10 18:20 UTC, stella3d approved these changes

2022-08-24 16:58 UTC, merged