[sui framework] add `vec_map::remove_entry_by_idx`
MystenLabs/sui pull request #4193
Opened 2022-08-21 20:24 UTC by juzybits

2022-08-21 20:32 UTC, sblackshear reviewed
Looks excellent, thanks!

Would you mind adding some tests for the success and failure case in https://github.com/MystenLabs/sui/blob/17f6960f8c1ab034ab05f00e5d6babb2877f451f/crates/sui-framework/tests/vec_map_tests.move ?

2022-08-21 21:38 UTC, juzybits commented
Done!
In addition to the new tests for `remove_entry_by_idx`, I pushed an additional commit modifying an existing test that looked like a copy/paste mistake.

2022-08-22 03:19 UTC, sblackshear approved these changes
Good catch on the older test

2022-08-22 03:26 UTC, sblackshear commented
Ah, I forgot there's one more step to go through here. Adding a new function to the Sui framework changes the genesis blob, and we have snapshots of this blob that need to be updated. Please do:

```
cargo install cargo-insta
cd sui/crates/sui-config/tests # where the snapshots live
cargo insta review # type a to accept genesis snapshot changes
cargo insta test # to verify changes
```

2022-08-22 03:27 UTC, sblackshear requested changes
For updating the genesis snaphsot

2022-08-22 15:43 UTC, juzybits commented
That seems to have worked (it updated `crates/sui-config/tests/snapshots/snapshot_tests__empty_genesis_snapshot_matches.snap`).

2022-08-22 17:30 UTC, sblackshear commented
I think `crates/sui-cost` has a snapshot that needs to be updated in a similar way

2022-08-22 20:16 UTC, juzybits commented
Done! Results show that `computationCost` increased by 1 in some cases like `Publish` - I guess this is to be expected.

Cool tooling :). I'll try to keep all this in mind for the future.

2022-08-25 13:50 UTC, juzybits commented
Rebased my changes on top of `main` to avoid merge conflicts.

2022-09-09 17:26 UTC, sblackshear approved these changes

2022-09-09 19:26 UTC, merged