[explorer] Enabling localnet e2e tests
MystenLabs/sui pull request #4416
Opened 2022-08-31 20:20 UTC by Jordan-Mysten

This adds a new suite of tests that run against localnet. I'm trying to break these tests up more so that they can be written and maintained a little easier. Right now, I'm keeping static tests, and will be slowly moving more over to the localnet tests.

### Running tests

1. Start the `sui-test-validator`. I use `cargo run --bin sui-test-validator`.
2. Start the explorer using `pnpm --filter sui-explorer dev:local`.
3. Open cypress with `pnpm --filter sui-explorer exec cypress open`.

You should now be able to execute the localnet tests!

2022-09-01 10:23 UTC, Andrew47 requested changes
There needs to be more clarity on the value of having these tests specifically against localnet. It adds a requirement that a local network needs to be spun up, which is another thing to go wrong. The original plan proposed by the backend engineers was that we were going to set up tests against the files in `crates/sui-open-rpc/samples`. The backend engineers could then re-generate these files upon breaking changes in the network. Why are we moving away from this plan?

2022-09-01 10:38 UTC, Andrew47 commented
Having tried to run `cargo run --bin sui-test-validator` locally, turns out the local network breaking is not theoretical:

![image](https://user-images.githubusercontent.com/11377188/187894674-cfcc1573-2941-4f39-b960-d16e2773adbb.png)

Could a list of requirements for running these tests be provided?

2022-09-01 20:39 UTC, todd-mystenlabs commented
Hey folks!

I fully support this change here.  As an entire team, we've taken many hits to productivity when we've unintentionally broken the explorer, wallet, etc.  I want, as closely as possible, for all of us to know that a given change (PR) is in a consistent state across both the Sui core and the other apps that build on it within the repo. @Andrew47 - hopefully that covers your concern there.  It's about the whole team having a stable, known, working main branch at all times.

2022-09-02 10:24 UTC, Andrew47 approved these changes
Thank you very much @Jordan-Mysten for the explanation.

2022-09-02 14:59 UTC, 666lcz commented
Not sure why, the `home page` tests pass but the `search` test fails for me
![CleanShot 2022-09-02 at 07 57 48](https://user-images.githubusercontent.com/76067158/188177393-07a1dd2b-32b0-45e5-bfe7-ba981d1fb64d.png)

2022-09-02 20:38 UTC, 666lcz approved these changes

2022-09-02 20:40 UTC, 666lcz commented on explorer/client/cypress/localnet.ts
> +                'http://localhost:9123/faucet',
Works for me locally after this change
```suggestion
                'http://127.0.0.1:9123/faucet',
```

2022-09-02 23:54 UTC, merged