[Explorer] Prevents collision when owned object has more text
MystenLabs/sui pull request #4529
Opened 2022-09-08 18:58 UTC by Andrew47

#### The Problem

The problem is that when the owned objects have long pieces of summary text, this text collides. This can be seen here: https://explorer.devnet.sui.io/addresses/0x9b598c9c5f28c94a660d3cbc047f67a510a60e7a 

![image](https://user-images.githubusercontent.com/11377188/189203041-9b2599b1-6438-4542-8138-ecee7c946c45.png)

#### The Solution in Action

##### With longer text

![image](https://user-images.githubusercontent.com/11377188/189203235-d1db9809-e30d-4e8d-be06-b199c8f89681.png)
![image](https://user-images.githubusercontent.com/11377188/189203333-758e8b6e-6904-4cca-8994-bddd78997e49.png)

#### With shorter text
![image](https://user-images.githubusercontent.com/11377188/189203498-18867ddd-8458-46a9-86c4-d22c7ea551a2.png)
![image](https://user-images.githubusercontent.com/11377188/189203689-38d5ccb4-e082-44e8-b7e7-09b7141d94a4.png)

2022-09-09 03:30 UTC, mystie711 requested changes
@Andrew47 in addition to adding details for rules (max line of text to show) i have also added details for small screen size breakpoints in this Figma here,
https://www.figma.com/file/kSD0qXCIDZA4KQVNepA5hR/02-Explorer?node-id=204%3A48379

2022-09-13 11:30 UTC, Andrew47 commented
Following the updated Figma Design, how the problem of collision is met has has been updated to now add an ellipsis when text overruns 3 lines.

The below screenshot was captured on Mozilla Firefox, but the effect is the same on Google Chrome, Microsoft Edge and Safari:

![image](https://user-images.githubusercontent.com/11377188/189889758-1c9ec9f2-bad4-4fb0-85a3-ff3f1181d685.png)

2022-09-13 14:26 UTC, mystie711 requested changes
Looking much better @Andrew47 . May I request a few more tweaks to improve the layout,

- padding between columns -> 40px
- empty placeholder asset when we don’t have an image -> use the assets with the image icon in Figma
- padding between image and text should be 15 (looks a lot more in the screenshot attached to task)
- space between items on mobile - let’s update it to 10px (new request)

2022-09-13 14:27 UTC, mystie711 commented
Totally lost track of plot. this task is not meant for the updates in my last comment. 
will file a new task for it. Please ignore my comments above.

2022-09-13 14:29 UTC, mystie711 approved these changes

2022-09-13 14:45 UTC, Jibz1 approved these changes

2022-09-13 14:46 UTC, merged