[framework] Emits coin::CreatedCurrency metadata + compiles book examples
MystenLabs/sui pull request #4558
Opened 2022-09-11 21:47 UTC by damirka

- Implements suggestion from #4551. Now call to `create_currency` emits `coin::CreatedCurrency` event.
- Adds code from examples book to framework tests (this way we make sure they always compile)

2022-09-11 23:49 UTC, sblackshear reviewed
Shouldn't this need to specify the `decimals` for `SUI` somewhere?

2022-09-11 23:49 UTC, sblackshear commented on crates/sui-framework/sources/coin.move
> +        decimals: u8
```suggestion
        /// Number of decimal places the coin uses. 
        /// A coin with `value ` N and `decimals` D should be shown as N / 10^D
        /// E.g., a coin with `value` 7002  and decimals 3 should be displayed as 7.002
        /// This is metadata for display usage only.
        decimals: u8
```

porting over comments from the other PR

2022-09-12 08:47 UTC, damirka commented
> Shouldn't this need to specify the `decimals` for `SUI` somewhere?

Nice catch. SUI is created through balance and we don’t have a TC for it, balance::Supply<SUI> is stored inside the SuiSystem. 

I wonder if we should eventually instantiate SUI with an OTW but that’s def gonna be tricky.

2022-09-12 08:51 UTC, damirka commented
This change introduces a whole set of questions related to balances (as in not Coins). 

But I believe that we should keep these functions around Coins while keeping the balance module. Happy to hear your thoughts @sblackshear!

2022-09-12 15:56 UTC, sblackshear commented
I didn't realize that there is no TC for Sui--I think it's useful to have one + put it inside `SuiSystem` in case there are future governance proposals that require (e.g.) burning Sui. 

In terms of coin vs balance vs supply, I must admit I still don't have a great understanding of when a programmer would use each of these three (probably a good topic for a future doc on coins and fungible tokens). But in the absence of other info, I would imagine that `decimals` and other token metadata would be relevant for all three of these.

2022-09-18 20:44 UTC, sblackshear requested changes
until we can figure out how to support decimals for SUI

2022-09-18 22:00 UTC, damirka commented
@sblackshear since we know that sui::SUI is a special case in verifier and can be constructed outside initializer, I’ll submit a patch to return TC instead of Supply in a couple days.

2022-09-28 12:43 UTC, damirka commented
@sblackshear Sorry for the delay. SUI is now initialized through `coin::create_currency`.

2022-09-28 21:15 UTC, sblackshear requested changes

2022-09-28 21:15 UTC, sblackshear commented on crates/sui-framework/sources/coin.move
> +        /// E.g., a coin with `value` 7002  and decimals 3 should be displayed as 7.002
```suggestion
        /// E.g., a coin with `value` 7002 and decimals 3 should be displayed as 7.002
```

2022-09-28 21:15 UTC, sblackshear commented on crates/sui-framework/sources/sui.move
> +            coin::create_currency(SUI {}, 6, ctx)
```suggestion
            coin::create_currency(SUI {}, 9, ctx)
```

The minimum unit is 10^-9 SUI, which we call a "mist" (i.e., 1 nano-SUI = 1 mist). I think we should also have a comment explaining this, perhaps on a `DECIMALS` constant so this information is easier to discover for someone reading the module?

2022-09-28 23:02 UTC, sblackshear approved these changes

2022-09-28 23:48 UTC, merged