[simtest] Move a fullnode test to simtest
MystenLabs/sui pull request #6045
Opened 2022-11-11 16:10 UTC by lxfind

2022-11-14 17:44 UTC, mystenmark requested changes

2022-11-14 19:58 UTC, lxfind commented on crates/sui/tests/full_node_tests.rs
> +    };
Could you point to me an example of how it should be written?

2022-11-16 17:47 UTC, mystenmark commented on crates/sui/tests/full_node_tests.rs
> +    };
sorry for not being clear. you can just write:

       let node = start_a_fullnode(&test_cluster.swarm, false).await.unwrap();

and remove the if/else.

2022-11-23 15:51 UTC, mystenmark approved these changes

2022-11-23 16:40 UTC, merged