[narwhal / bullshark] Delete dynamic committee change + epoch change from NW
MystenLabs/sui pull request #6191
Opened 2022-11-18 16:27 UTC by gdanezis

The logic to dynamically configure the committee and epoch in narwhal was fragile, and difficult to reason about and maintain. We are moving to an approach where we start separate fresh instances of primaries and workers for epochs or even within epochs. This PR removes the NewEpoch and CommitteeChange messages, the logic they called and the tests that test them.

2022-11-18 18:02 UTC, andll approved these changes
This is epic! This `committee.load()` and online worker reconfiguration was indeed scary part of the code.

2022-11-18 18:11 UTC, bmwill commented on narwhal/node/src/restarter.rs
> +            // worker_cache.swap(Arc::new(new_worker_cache));
remove?

2022-11-18 18:11 UTC, akichidis requested changes
Haven't reviewed the PR yet - so this is not a blocker to change something :-) - but as I am still evaluating the reconfiguration path I would like to hold and not merge until confirmed the plan. @gdanezis thanks for the PR!

2022-11-18 18:13 UTC, bmwill approved these changes

2022-11-29 02:26 UTC, laura-makdah reviewed
I don't see any major issues. Thanks!

2022-11-29 02:26 UTC, laura-makdah commented on narwhal/node/src/lib.rs
> +        let (tx_shutdown, _rx_shutdown) = watch::channel(initial_committee);
will there be a need to read the committee from the channel when it is now only being used as shutdown?

2022-11-29 02:26 UTC, laura-makdah commented on narwhal/node/src/lib.rs
> +            tx_shutdown.subscribe(),
nit: let's also unify our approach to either pass receivers, or senders which are then used to subscribe in the spawned component (this is the only outlier?)

2022-12-01 03:33 UTC, asonnino approved these changes

2022-12-01 14:43 UTC, akichidis commented on narwhal/node/tests/reconfigure.rs
> -async fn restart() {
Let's keep this test, it is needed as it is testing the reconfiguration approach via the `restart/shutdown` method. I'll rebase the PR as I've made some changes on this test

2022-12-01 16:10 UTC, akichidis commented on narwhal/primary/src/grpc_server/configuration.rs
> -        request: Request<NewNetworkInfoRequest>,
As far as I remember this was a request from Celo/Sommelier. The idea is that networking information might not be available from the beginning and change down the line. It seems that with this PR we are removing completely this ability. Apart from that, I am not convinced that this endpoint was working correctly even before either. It seems that we do swap the committee , but never update the actual networking info via anemo. That being said I would at least add here a TODO to indicate a breaking behaviour

2023-01-03 10:47 UTC, closed without merging