Add another example for how to use drand with single-owner objects
MystenLabs/sui pull request #6239
Opened 2022-11-21 08:42 UTC by benr-ml

2022-11-21 08:44 UTC, benr-ml commented
@kchalkias no tests yet, just implemented the main logic. Please take a look and see if you have comments about the general design. Note that we need at least 2 epochs since users cannot check when an epoch began at the moment.

2022-11-22 01:22 UTC, kchalkias requested changes

2022-11-22 01:22 UTC, kchalkias commented on sui_programmability/examples/games/sources/drand_based_scratch_card.move
> +        creator: address,
Awesome! yes this pattern!

2022-11-22 01:22 UTC, kchalkias commented on sui_programmability/examples/games/sources/drand_based_scratch_card.move
> +    /// Buy a ticket for a specific game, costing reward/RewardFactor SUI. Can be called only during the epoch in which
reward/RewardFactor either maintain lowercase `reward/reward_factor` or Reward with capital R `Reward/RewardFactor`

2022-11-22 01:22 UTC, kchalkias commented on sui_programmability/examples/games/sources/drand_based_scratch_card.move
> +/// - Reward - a shared object that holds the reward. It can be withdrawn by any winner ("first come, first served").
I'm happy to publish this game type, but ideally due to this FCFS rule we shouldn't recommend this pattern in practice for most real world applications. We need a warning message at the top of this file, if we keep this game.

Ideally, for the future we need a multi-player game with sortition and challenge period, to ensure one winner.

2022-11-22 01:22 UTC, kchalkias commented on sui_programmability/examples/games/sources/drand_based_scratch_card.move
> +/// Anyone can create a new game by depositing X*100 SUIs as a reward, and setting the current drand round as the base
**Let's make clear that the prize is fixed and independent on the num purchased tickets**. This is an important detail and the most common question (also the pattern on when this single write approach can be applied securely).

2022-11-24 15:17 UTC, kchalkias approved these changes

2022-11-24 15:17 UTC, kchalkias commented on sui_programmability/examples/games/sources/drand_based_scratch_card.move
> +/// Importnat: There is 1 reward per game, and there is no limit on the number of tickets that can be bought for a
Importa**nt** (typo)

2022-11-24 15:17 UTC, kchalkias commented on sui_programmability/examples/games/sources/drand_based_scratch_card.move
> +/// One may extend this game and add another round in which winners can register their winner tickets, and then one of
Thanks!!

2022-11-24 15:17 UTC, kchalkias commented on sui_programmability/examples/games/sources/drand_based_scratch_card.move
> +        round + 2 * 60 * (24 + 25)
Indeed, acceptable assumption

2022-11-24 21:27 UTC, merged