Add object id validity test #SUI-55
MystenLabs/sui pull request #6414
Opened 2022-11-28 11:40 UTC by xydas97

Work for implementation of ticket https://mysten.atlassian.net/browse/SUI-55?atlOrigin=eyJpIjoiMTczNDQwMjdhOGNjNDFhZThhZmZmYmU5NDYxODYwNGUiLCJwIjoiaiJ9

2022-11-28 11:46 UTC, xydas97 commented
ts-sdk: check if object id /address/transaction digest is valid before querying fullnode

2022-11-30 19:34 UTC, 666lcz requested changes
Thanks for working on this! Overall looks good with a few places to fix.

2022-11-30 19:34 UTC, 666lcz commented on sdk/typescript/src/providers/json-rpc-provider.ts
> +      if (!isValidSuiAddress(normalizeSuiAddress(address)) || !address) {
```suggestion
      if (!address || !isValidSuiAddress(normalizeSuiAddress(address))) {
```
nit: can we put `!address` at the front`?

2022-11-30 19:34 UTC, 666lcz commented on sdk/typescript/src/providers/json-rpc-provider.ts
> +      if (!isValidSuiObjectId(normalizeSuiObjectId(objectId)) || !objectId) {
ditto

2022-11-30 19:34 UTC, 666lcz commented on sdk/typescript/src/providers/json-rpc-provider.ts
> +      if (!isValidSuiObjectId(normalizeSuiObjectId(objectId)) || !objectId) {
ditto

2022-11-30 19:34 UTC, 666lcz commented on sdk/typescript/src/providers/json-rpc-provider.ts
>      const requests = objectIds.map((id) => ({
We should also validate each of the `objectIds` here. If one of them is invalid, feel free to throw an error that tells which of the `objectIds` is invalid.

2022-11-30 19:34 UTC, 666lcz commented on sdk/typescript/src/providers/json-rpc-provider.ts
> +      if (!isValidSuiObjectId(normalizeSuiObjectId(objectID)) || !objectID) {
ditto

2022-11-30 19:34 UTC, 666lcz commented on sdk/typescript/src/providers/json-rpc-provider.ts
> +      if (!isValidSuiAddress(normalizeSuiAddress(addressID)) || !addressID) {
ditto

2022-11-30 19:34 UTC, 666lcz commented on sdk/typescript/src/providers/json-rpc-provider.ts
> +      if (!isValidTransactionDigest(digest)) {
We also need to do the same validation for `getTransactionWithEffectsBatch` on line 546

2022-12-09 15:56 UTC, 666lcz commented on sdk/typescript/src/providers/json-rpc-provider.ts
> +        if (!isValidTransactionDigest(d, "base64") && !isValidTransactionDigest(d, "base58")) {
```suggestion
        if (!isValidTransactionDigest(d, "base58")) {
```
We have released `0.18.0` on DevNet, which uses `base58`, so we no longer need this check.


@joyqvq do you mind cleaning up the pre-0.18.0 code?

2022-12-09 15:57 UTC, 666lcz commented on sdk/typescript/src/providers/json-rpc-provider.ts
> +      if (!isValidTransactionDigest(digest, "base64") && !isValidTransactionDigest(digest, "base58")) {
```suggestion
      if (!isValidTransactionDigest(digest, "base58")) {
```

2022-12-09 17:35 UTC, merged