[coin.move] CoinMetadata getter functions for on-chain inspection
MystenLabs/sui pull request #6911
Opened 2022-12-19 17:33 UTC by optke3

- Currently, `CoinMetadata` can be accessed for off-chain consumption, however there is a class of use-cases where we would like to consume the metadata fields (decimals, name, symbol, etc.) on-chain. For example, a protocol might want to perform checks on the metadata corresponding to a `CoinType` on-chain, e.g. check that `decimals==8`. Currently this is impossible because the metadata fields are opaque. The following getters allow inspection of `CoinMetadata` object fields.

2022-12-19 18:53 UTC, 666lcz approved these changes

2022-12-20 11:09 UTC, amnn commented
Thanks for the contribution @optke3!

The test failures come from our snapshot tests for genesis and gas costs which have changed because your change affects the framework library (which is published as part of genesis, and loaded by the transactions that calibrate gas costs).  To fix these please:

- Rebase your commit (there were some recent changes for gas costing).
- Go to the `sui-cost` crate (`sui/crates/sui-cost`), run `cargo insta test --review`, and accept the changes.
- Go to the `sui-config` crate (`sui/crates/sui-config`), run `cargo insta test --review` there, and accept those changes as well.
- Commit the snapshot changes.

You may need to install insta.rs for this as well (`cargo install cargo-insta`).

2022-12-22 14:57 UTC, amnn requested changes
It looks like you still need to run the `cargo insta --review` commands, sending the PR back to you for that.

2022-12-23 10:40 UTC, amnn approved these changes
Good to go, thanks again @optke3 !

2022-12-23 10:40 UTC, merged