Change tx_seq -> tx_digest of EventID (WIP)
MystenLabs/sui pull request #6944
Opened 2022-12-20 16:33 UTC by xydas97

2023-01-11 17:12 UTC, patrickkuo requested changes

2023-01-11 17:12 UTC, patrickkuo commented on crates/sui-indexer/src/models/events.rs
> +    //pub transaction_sequence: i64,
we should remove this line

2023-01-11 17:12 UTC, patrickkuo commented on crates/sui-indexer/src/models/events.rs
> +        //transaction_sequence: e.id.tx_seq,
ditto

2023-01-11 17:12 UTC, patrickkuo commented on crates/sui-json-rpc/src/event_api.rs
> +                id: EventID::from((e.tx_digest.unwrap(), e.event_num as i64)),
we should make EventEnvelope::tx_digest non-optional, I don't think this is ever None

2023-01-12 08:58 UTC, xydas97 commented on crates/sui-indexer/src/models/events.rs
> +    //pub transaction_sequence: i64,
yes, I missed that

2023-01-12 14:52 UTC, patrickkuo commented on sdk/typescript/src/providers/json-rpc-provider.ts
> +    start: TransactionDigest,
we shouldn't need to change this...

2023-01-12 22:39 UTC, patrickkuo approved these changes
just one comment on the GatewayTxSeqNumber changes, otherwise LGTM

2023-01-12 22:39 UTC, patrickkuo commented on sdk/typescript/src/providers/json-rpc-provider.ts
> +  GatewayTxSeqNumber,
nit: lets revert all GatewayTxSeqNumber changes in this PR, we don't need to have this in commit history.

2023-01-13 12:36 UTC, merged