[explorer] remove static dev mode /  code branching
MystenLabs/sui pull request #7364
Opened 2023-01-12 22:07 UTC by mamos-mysten

- removes static dev mode and related code

2023-01-12 22:34 UTC, Jordan-Mysten requested changes

2023-01-12 22:34 UTC, Jordan-Mysten commented on apps/explorer/src/utils/searchUtil.ts
> -    import('./static/searchUtil').then((uf) => {
Can we also remove this file?

2023-01-12 22:34 UTC, Jordan-Mysten commented on apps/explorer/src/utils/searchUtil.ts
> +import('./api/searchUtil').then(
This can just statically be imported now, no need to use dynamic imports with this reassignment nonsense.

2023-01-12 22:34 UTC, Jordan-Mysten commented on apps/explorer/vite.config.ts
> +    cacheDir: 'node_modules/.vite',
This is the default, just remove this.

2023-01-12 22:34 UTC, Jordan-Mysten commented on apps/explorer/src/pages/transactions/Transactions.tsx
> +    return <TransactionsAPI />;
Remove this wrapping component, not needed anymore.

2023-01-12 22:34 UTC, Jordan-Mysten commented on apps/explorer/src/components/transaction-card/TxForID.tsx
> +    return <TxForIDAPI id={id} category={category} />;
Can you remove the parent component that just does this branching?

2023-01-12 22:34 UTC, Jordan-Mysten commented on apps/explorer/src/components/ownedobjects/OwnedObjects.tsx
>  function OwnedObject({ id, byAddress }: { id: string; byAddress: boolean }) {
Remove indirection component

2023-01-12 22:34 UTC, Jordan-Mysten commented on apps/explorer/src/components/network-stats/SuiNetworkStats.tsx
> +    return <SuiNetworkCard count={count} />;
Remove indirection component

2023-01-12 22:40 UTC, mamos-mysten commented on apps/explorer/src/utils/searchUtil.ts
> -    import('./static/searchUtil').then((uf) => {
yep, my bad thought I had done that.

2023-01-13 00:20 UTC, Jordan-Mysten approved these changes
Glad we get to remove all of this code!

2023-01-13 02:37 UTC, merged