Explorer validator sorting
MystenLabs/sui pull request #7481
Opened 2023-01-18 18:36 UTC by Jibz1

https://user-images.githubusercontent.com/8676844/213721479-facc840a-6829-47b8-a34b-d057a0d3ec58.mov

2023-01-19 14:13 UTC, mystie711 approved these changes
@Jibz1 following up on our conversation yesterday,
- default sort by stake
- remove unsorted state

2023-01-20 21:44 UTC, mamos-mysten requested changes

2023-01-20 21:44 UTC, mamos-mysten commented on apps/explorer/src/ui/TableCard.tsx
> +    //  type ColumnDef,
can we make use of this type?

2023-01-20 21:44 UTC, mamos-mysten commented on apps/explorer/src/ui/TableCard.tsx
> +    const processedcol = useMemo(
we can improve typings here e.g. `useMemo<ColumnDef<TableData>[]> where `TableData` is a type representing the data in the table

2023-01-20 23:21 UTC, Jibz1 commented on apps/explorer/src/ui/TableCard.tsx
> +                                        className="h-7.5 px-1 text-body text-gray-75 group-hover:bg-gray-40 group-hover:text-gray-90 group-hover:first:rounded-l group-hover:last:rounded-r"
I think some of the transaction fields use the default style. Like the `gas` fields. The current implementation of the table data needs to be corrected. We must pass the data to the table data field and components in the column. I will create separate takes for that. Once we have that, we can remove the text style.

2023-01-20 23:46 UTC, Jordan-Mysten commented on apps/explorer/src/ui/TableCard.tsx
> +                                        className="h-7.5 px-1 text-body text-gray-75 group-hover:bg-gray-40 group-hover:text-gray-90 group-hover:first:rounded-l group-hover:last:rounded-r"
I'll probably pull together a rework for the table in another PR, so don't stress about that.

2023-01-21 20:09 UTC, Jibz1 commented on apps/explorer/src/ui/TableCard.tsx
> +                                                    <ArrowRight
done

2023-01-21 20:13 UTC, Jibz1 commented on apps/explorer/src/ui/TableCard.tsx
> +    //  type ColumnDef,
done

2023-01-22 06:51 UTC, Jordan-Mysten approved these changes
Approving to unblock but some nits

2023-01-22 06:51 UTC, Jordan-Mysten commented on apps/explorer/src/pages/validators/Validators.tsx
> +                            </div>{' '}
Extra space

2023-01-22 06:51 UTC, Jordan-Mysten commented on apps/explorer/src/pages/validators/Validators.tsx
> +                cell: (props: any) => (
Don't love the `any`'s here. We can follow-up later with an improved Table component, just want to call it out

2023-01-22 06:51 UTC, Jordan-Mysten commented on apps/explorer/src/pages/validators/Validators.tsx
> +        return parseFloat(
Probably generalize into function.

2023-01-22 06:51 UTC, Jordan-Mysten commented on apps/explorer/src/ui/TableCard.tsx
> +                                                : void 0
Just use `undefined`?

2023-01-22 06:51 UTC, Jordan-Mysten commented on apps/explorer/src/ui/TableCard.tsx
> +                                            }[column.getIsSorted() as string] ??
Just make a component <SortIcon /> that can take in a prop that's `asc` or `desc` and return the correct icon based on that. Will be easier to follow.

2023-01-23 21:55 UTC, merged