(wip) wallet-ext: account selector
MystenLabs/sui pull request #7628
Opened 2023-01-24 11:22 UTC by pchrysochoidis

2023-02-01 18:51 UTC, mystie711 commented
@pchrysochoidis realized one small delta in Figma that i have now updated.
For single wallet interaction, on-hover over the pill, could we also have the icon be colorized?
<img width="290" alt="image" src="https://user-images.githubusercontent.com/109102528/216135740-ebfffab6-1366-4c6f-b7ca-10e4acb7e062.png">

2023-02-01 21:43 UTC, mystie711 approved these changes
looking good.

2023-02-01 22:54 UTC, pchrysochoidis commented
> @pchrysochoidis realized one small delta in Figma that i have now updated. For single wallet interaction, on-hover over the pill, could we also have the icon be colorized? <img alt="image" width="290" src="https://user-images.githubusercontent.com/109102528/216135740-ebfffab6-1366-4c6f-b7ca-10e4acb7e062.png">

Updated it


https://user-images.githubusercontent.com/10210143/216184143-1f4899f3-4450-40c1-a32d-049849c96405.mov


https://user-images.githubusercontent.com/10210143/216184153-69fb0970-af86-4b94-8512-35a1f0aac4d8.mov

2023-02-02 23:18 UTC, mamos-mysten requested changes

2023-02-02 23:46 UTC, pchrysochoidis commented
Thanks @mamos-mysten, I updated the animation to 200ms and added the hover state


https://user-images.githubusercontent.com/10210143/216476476-ea60a5a6-7afe-4276-9bd1-fd433a650b0e.mov

2023-02-03 02:58 UTC, mamos-mysten approved these changes
looks good to me

2023-02-03 12:57 UTC, merged