[TypeScript SDK] Add "win-prepare:e2e" for Windows machines
MystenLabs/sui pull request #8136
Opened 2023-02-07 10:36 UTC by xydas97

Fix for this issue https://github.com/MystenLabs/sui/issues/8134

2023-02-19 06:21 UTC, 666lcz approved these changes

2023-02-20 09:39 UTC, xydas97 commented
Added a simple script command to prepare e2e tests for Windows machines and included it in the sdk documentation. If you can please review the PR so that it can be merged.
cc @randall-Mysten

2023-02-21 16:53 UTC, Jordan-Mysten requested changes
Instead of making separate scripts, let's use something like cross-env to make these compatible with both: https://www.npmjs.com/package/cross-env

2023-03-02 23:22 UTC, Jordan-Mysten approved these changes

2023-03-03 08:43 UTC, merged