Batch read txn api
MystenLabs/sui pull request #8480
Opened 2023-02-21 13:57 UTC by siomari

Implemented methods for get transactions in batch in sui-json-rpc

2023-02-21 14:58 UTC, patrickkuo requested changes
some changes required but we are in the right direction.

2023-02-27 22:31 UTC, patrickkuo commented on crates/sui-json-rpc/src/read_api.rs
> +        for i in 0..txn_batch.len() {
you should be able to iterate txn_batch instead of index
```
 for txn in txn_batch{
...
```

2023-02-27 22:31 UTC, patrickkuo commented on crates/sui-core/src/authority.rs
> +    }
if you can ensure the order of multi_get_transaction and multi_get_transaction_checkpoint (we can ensure it by doing [this](https://github.com/MystenLabs/sui/blob/513c2902a1af9aa62445f9aa62c8aeabf8fe2cc1/crates/sui-core/src/authority/authority_store.rs#L193-L196)), you can zip all of them together and check for missing data: 
```
        let mut missed_digests = vec![];
        let mut response: VerifiedTransactionBatch = vec![];

        for data in izip!(digests, transactions, effects, checkpoints) {
            match data {
                (_, Some(tx), Some(effect), cp) => response.push(((tx, effect), cp)),
                (digest, _, _, _) => missed_digests.push(*digest),
            }
        }

        if !missed_digests.is_empty() {
            Err(anyhow!(SuiError::TransactionsNotFound {
                digests: missed_digests
            }))
        } else {
            Ok(response)
        }
```

2023-02-27 22:31 UTC, patrickkuo commented on crates/sui-json-rpc/src/read_api.rs
> +        let txn_batch = self
we should ensure there are no duplicates and also limit the number of digest before any processing.

we can use `QUERY_MAX_RESULT_LIMIT` for now

2023-03-02 11:22 UTC, patrickkuo commented on crates/sui-json-rpc/src/read_api.rs
> +            .collect();
lets return error if it reached the limit

2023-03-02 11:31 UTC, patrickkuo reviewed
just a few minor comments, almost good to go.

2023-03-02 11:31 UTC, patrickkuo commented on crates/sui-json-rpc/src/read_api.rs
> +        for (txn, digest) in txn_batch.iter().zip(tx_digests.iter()) {
if you change this to `into_iter`, you won't need to clone later

2023-03-02 11:31 UTC, patrickkuo commented on crates/sui-json-rpc/src/read_api.rs
> +                transaction: txn.clone().0 .0.into_message().try_into()?,
it's better to destructure `txn` instead of doing `txn.0.0` ...

2023-03-02 15:56 UTC, patrickkuo approved these changes
LGTM! Nice work!

2023-03-03 13:50 UTC, merged

2023-03-06 03:50 UTC, 666lcz commented on crates/sui-json-rpc/src/read_api.rs
> +                    timestamp_ms: self.state.get_timestamp_ms(digest).await?,
@gegaowp @patrickkuo should this be `checkpoint.as_ref().map(|c| c.summary.timestamp_ms)` instead?