fix explorer showing NFT owned by two addresses
MystenLabs/sui pull request #8621
Opened 2023-02-24 16:28 UTC by Jibz1

## Description 

Under the address 0xbbf6e1a24a7b71a33699d08de47e5e41da879512  appears the NFT with object id 0x93e5265cf2439a19fe13e57035eb3b3cd420cc13  but the owner of that NFT is 0x81209693a0c393cdcefd548e891107aaeb024eb9 . The same NFT with the exact object id appears also under the address 0x81209693a0c393cdcefd548e891107aaeb024eb9  which is the original owner.

## Test Plan 

---
If your changes are not user-facing and not a breaking change, you can skip the following section. Otherwise, please indicate what changed, and then add to the Release Notes section as highlighted during the release process.

### Type of Change (Check all that apply)

- [x ] user-visible impact
- [ ] breaking change for a client SDKs
- [ ] breaking change for FNs (FN binary must upgrade)
- [ ] breaking change for validators or node operators (must upgrade binaries)
- [ ] breaking change for on-chain data layout
- [ ] necessitate either a data wipe or data migration

### Release notes

2023-02-24 16:45 UTC, Jordan-Mysten approved these changes

2023-03-04 00:07 UTC, Jordan-Mysten requested changes

2023-03-04 00:07 UTC, Jordan-Mysten commented on apps/explorer/src/components/ownedobjects/OwnedObjects.tsx
> +                                ) as {
Lets avoid these casts

2023-03-21 23:01 UTC, Jibz-Mysten commented
closing this PR for https://github.com/MystenLabs/sui/pull/9670

2023-03-21 23:01 UTC, closed without merging