Adding FN call for multiget objects
MystenLabs/sui pull request #9030
Opened 2023-03-08 21:21 UTC by healthydeve

## Description 

Adding FN api call for multiGet objects
## Test Plan 

unit testing
---
If your changes are not user-facing and not a breaking change, you can skip the following section. Otherwise, please indicate what changed, and then add to the Release Notes section as highlighted during the release process.

### Type of Change (Check all that apply)

- [ ] user-visible impact
- [ ] breaking change for a client SDKs
- [ ] breaking change for FNs (FN binary must upgrade)
- [ ] breaking change for validators or node operators (must upgrade binaries)
- [ ] breaking change for on-chain data layout
- [ ] necessitate either a data wipe or data migration

### Release notes

2023-03-08 23:00 UTC, 666lcz requested changes
Thanks for the quick PR! Overall looks good to me, requesting changes for some small nits

2023-03-09 17:32 UTC, healthydeve commented on crates/sui-json-rpc/src/read_api.rs
> +                            (object_ref, o, layout, options_clone, display_fields).try_into()?,
I just used the existing function instead so that we don't repeat code.

2023-03-09 19:42 UTC, 666lcz approved these changes
Great work!

2023-03-09 19:42 UTC, 666lcz commented on crates/sui-json-rpc/src/api/read.rs
> +    /// Return the object information for a specified object
```suggestion
    /// Return the object data for a list of objects
```

2023-03-09 21:07 UTC, merged