[Authority + Adapter] Add package caching, and remove redundant digest checks + clones
MystenLabs/sui pull request #963
Opened 2022-03-19 21:00 UTC by gdanezis

Looking at the profiler and flamegraphs given the latest batching benchmark: 
* Problem: we spend a significant amount of time hashing objects as part of checking locks. However an input object with an incorrect digest will result in the transaction or certificate subsequently not finding the lock on the locks table and being rejected. Solution: Therefore I have commented out the check.
* Problem: we spend a very log time re-de-serializing packages to determine their module id, and also their function signatures. Solution: now I made a cache next to the movevm that all threads share and that caches packages and their pre-computed functions.

On my laptop I see throughput go from 35K -> 45K TPS on move batched (100) benchmarks, and nearly no gap now between native transfer and move execution.

2022-03-22 12:22 UTC, gdanezis commented
> > The package cache is shared, along with the movevm that is associated with the AuthorityState:
> > https://github.com/MystenLabs/sui/blob/f8c1b5963a6352ea26e6b9dd27f75257ced6f148/sui_programmability/adapter/src/adapter.rs#L51-L60
> 
> I must be missing something important here: how is the movevm/cache shared? We create a new VM in serving each request, and the package cache is contained in that VM as well. So where exactly did we share it across requests?

Ah, I see. This has not changed, we create and re-use a shared move VM that we store in AuthorityState:
https://github.com/MystenLabs/sui/blob/40b870d5e09a920926886e2c173b60f54fb3206d/sui_core/src/authority.rs#L764-L778

This AuthorityState in turn is shared within the AuthorityServer across all threads.

2022-03-29 06:15 UTC, lxfind requested changes
LGTM overall but sending back to your queue regarding @huitseeker's comment.

2022-03-29 14:53 UTC, gdanezis commented
Re-enabled the check, to shortcut the discussion about whether it is needed or not.

2022-03-29 14:54 UTC, gdanezis commented on sui_core/src/authority.rs
> +                // hashes here.
Re enabled the check. We can afford to hash more.

2022-03-29 20:12 UTC, gdanezis commented
Many thanks for the review @lxfind and @huitseeker !

2022-03-29 20:54 UTC, merged